/* ==========================================================================
   Conteúdo pedagógico — extraído da aula "Minna no Nihongo 初級 I — Manual de
   Aulas, Método Chunk (Odu Creative)".
   Cada frase: "chunk:TIPO chunk:TIPO ... | tradução | distrator1, distrator2"
   TIPO: S = Sujeito · V = Verbo · O = Objeto/Complemento · A = Auxiliar/Partícula
         D = Advérbio/Expressão de tempo e lugar  (mesma legenda de cores da aula)
   Distratores por frase são opcionais; quando ausentes usa-se "dec" do ponto.
   ========================================================================== */
const LESSONS = [
{ n:1, t:"わたしはマイク・ミラーです",
  obj:["Apresentar-se e identificar pessoas com N1 は N2 です","Perguntar com ～ですか","Dizer \"também\" com も"],
  pts:[
  { k:"A", name:"Identificação com です", f:"N1 は N2 です", dec:["を","の"],
    err:["わたしはマイク・ミラー。","わたしはマイク・ミラーです。","Encerrar a oração sem です. No registro formal, a frase só se completa com です no final."],
    s:["わたし:S は:A マイク・ミラー:O です:V | Eu sou Mike Miller.",
       "ミラーさん:S は:A アメリカじん:O です:V | O Sr. Miller é americano.",
       "たなかさん:S は:A せんせい:O です:V | O Sr. Tanaka é professor.",
       "わたしたち:S は:A がくせい:O です:V | Nós somos estudantes."]},
  { k:"B", name:"Perguntas com ですか", f:"N1 は N2 ですか", dec:["？","が"],
    err:["あなたはがくせいです？","あなたはがくせいですか。","Usar \"？\" junto com か. A partícula か já transforma a frase em pergunta."],
    s:["あなた:S は:A がくせい:O です:V か:A | Você é estudante?",
       "ミラーさん:S は:A アメリカじん:O です:V か:A | O Sr. Miller é americano?",
       "たなかさん:S は:A いしゃ:O です:V か:A | O Sr. Tanaka é médico?",
       "カリナさん:S は:A インドネシアじん:O です:V か:A | A Karina é indonésia?"]},
  { k:"C", name:"\"Também\" com も", f:"N1 も N2 です", dec:["は","が"],
    err:["わたしはもがくせいです。","わたしもがくせいです。","Combinar は e も. Quando も entra, ele substitui は — nunca aparecem juntas."],
    s:["わたし:S も:A がくせい:O です:V | Eu também sou estudante.",
       "たなかさん:S も:A せんせい:O です:V | O Sr. Tanaka também é professor.",
       "わたしたち:S も:A ブラジルじん:O です:V | Nós também somos brasileiros.",
       "カリナさん:S も:A がくせい:O です:V | A Karina também é estudante."]}
  ]},
{ n:2, t:"これはほんです",
  obj:["Identificar objetos com これ／それ／あれ","Indicar posse com N1 の N2","Perguntar \"qual?\" com どれ／どの"],
  pts:[
  { k:"A", name:"これ／それ／あれ", f:"これ／それ／あれ は N です", dec:["この:S","どれ:S"],
    err:["これはほん。","これはほんです。","Encerrar a oração sem です."],
    s:["これ:S は:A ほん:O です:V | Isto é um livro.",
       "それ:S は:A じしょ:O です:V | Isso é um dicionário.",
       "あれ:S は:A ざっし:O です:V | Aquilo é uma revista.",
       "これ:S は:A しんぶん:O です:V | Isto é um jornal."]},
  { k:"B", name:"Posse com N1 の N2", f:"N1 の N2", dec:["が","に"],
    err:["これはわたしほんです。","これはわたしのほんです。","Esquecer の entre os dois substantivos. O japonês liga os nomes com の."],
    s:["これ:S は:A わたし:O の:A ほん:O です:V | Isto é o meu livro.",
       "これ:S は:A ミラーさん:O の:A じしょ:O です:V | Isto é o dicionário do Sr. Miller.",
       "それ:S は:A だれ:O の:A かさ:O です:V か:A | De quem é esse guarda-chuva?",
       "このほん:S は:A わたし:O の:A です:V | Este livro é meu."]},
  { k:"C", name:"Perguntas com どれ／どの", f:"どれですか／どの N ですか", dec:["は"],
    err:["どのはほんですか。","どのほんですか。","Usar どの sozinho. どの precisa de um substantivo logo depois; sozinho, use どれ."],
    s:["じしょ:S は:A どれ:O です:V か:A | Qual é o dicionário? | どの",
       "どの:A ほん:O です:V か:A | Qual livro é? | どれ",
       "ミラーさんのかさ:S は:A どれ:O です:V か:A | Qual é o guarda-chuva do Sr. Miller? | どの",
       "どの:A ざっし:O です:V か:A | Qual revista é? | どれ"]}
  ]},
{ n:3, t:"ここはデパートです",
  obj:["Identificar lugares com ここ／そこ／あそこ","Perguntar onde fica algo com ～はどこですか","Perguntar preços com いくらですか"],
  pts:[
  { k:"A", name:"ここ／そこ／あそこ", f:"ここ／そこ／あそこ は N です", dec:["どこ:S","これ:S"],
    err:["どこはデパートです。","ここはデパートです。","どこ só aparece em perguntas. Na afirmação, use ここ／そこ／あそこ."],
    s:["ここ:S は:A デパート:O です:V | Aqui é a loja de departamentos.",
       "そこ:S は:A えき:O です:V | Aí é a estação.",
       "あそこ:S は:A ゆうびんきょく:O です:V | Ali é o correio.",
       "ここ:S は:A うち:O です:V | Aqui é a minha casa."]},
  { k:"B", name:"～はどこですか", f:"N は どこですか", dec:["いくら","が"],
    err:["えきはどこです。","えきはどこですか。","Esquecer か no final da pergunta."],
    s:["えき:S は:A どこ:O です:V か:A | Onde fica a estação?",
       "トイレ:S は:A どこ:O です:V か:A | Onde fica o banheiro?",
       "じむしょ:S は:A どこ:O です:V か:A | Onde fica o escritório?",
       "かいぎしつ:S は:A どこ:O です:V か:A | Onde fica a sala de reuniões?"]},
  { k:"C", name:"Preço: いくらですか", f:"（これは）いくらですか", dec:["どこ","の"],
    err:["これはどこですか。","これはいくらですか。","Confundir interrogativos: どこ pergunta lugar, いくら pergunta preço."],
    s:["これ:S は:A いくら:O です:V か:A | Quanto custa isto?",
       "それ:S は:A いくら:O です:V か:A | Quanto custa isso?",
       "このかさ:S は:A いくら:O です:V か:A | Quanto custa este guarda-chuva?",
       "あのとけい:S は:A いくら:O です:V か:A | Quanto custa aquele relógio?"]}
  ]},
{ n:4, t:"そのりょかんはやすいです",
  obj:["Descrever com adjetivos イ","Descrever com adjetivos ナ","Indicar grau com とても／あまり／ぜんぜん"],
  pts:[
  { k:"A", name:"Adjetivos イ", f:"N は イadj です", dec:["な","を"],
    err:["このりょかんはやすい。","このりょかんはやすいです。","Encerrar a frase sem です."],
    s:["このりょかん:S は:A やすい:O です:V | Esta pousada é barata.",
       "そのビル:S は:A たかい:O です:V | Esse prédio é alto.",
       "このへや:S は:A おおきい:O です:V | Este quarto é grande.",
       "そのへや:S は:A ちいさい:O です:V | Esse quarto é pequeno."]},
  { k:"B", name:"Adjetivos ナ", f:"N は ナadj です", dec:["な","を"],
    err:["このへやはきれいなです。","このへやはきれいです。","な NÃO aparece antes de です — só antes de substantivos."],
    s:["このへや:S は:A しずか:O です:V | Este quarto é silencioso.",
       "このビル:S は:A きれい:O です:V | Este prédio é bonito.",
       "このえき:S は:A にぎやか:O です:V | Esta estação é movimentada.",
       "このまち:S は:A ゆうめい:O です:V | Esta cidade é famosa."]},
  { k:"C", name:"Grau: とても／あまり／ぜんぜん", f:"とても adj / あまり adj-ない", dec:["を"],
    err:["これはあまりやすいです。","これはあまりやすくないです。","あまり só aparece com negativa; com afirmativo, use とても."],
    s:["このりょかん:S は:A とても:D やすい:O です:V | Esta pousada é muito barata. | あまり:D",
       "そのビル:S は:A あまり:D たかくない:O です:V | Esse prédio não é muito alto. | とても:D, たかい",
       "このえき:S は:A ぜんぜん:D にぎやか:O じゃありません:V | Esta estação não é nada movimentada. | とても:D, です",
       "このへや:S は:A とても:D しずか:O です:V | Este quarto é muito silencioso. | あまり:D"]}
  ]},
{ n:5, t:"ミラーさんは7じにおきます",
  obj:["Conjugar ～ます／～ません","Conjugar ～ました／～ませんでした","Marcar horário com に"],
  pts:[
  { k:"A", name:"Presente ～ます／～ません", f:"V ます／ません", dec:["に","を"],
    err:["ミラーさんおきます。","ミラーさんはおきます。","Esquecer は após o sujeito."],
    s:["ミラーさん:S は:A まいあさ:D おきます:V | O Sr. Miller acorda cedo todas as manhãs.",
       "わたし:S は:A まいばん:D べんきょうします:V | Eu estudo todas as noites.",
       "ミラーさん:S は:A まいにち:D はたらきます:V | O Sr. Miller trabalha todos os dias.",
       "わたし:S は:A あした:D はたらきません:V | Eu não vou trabalhar amanhã."]},
  { k:"B", name:"Passado ～ました", f:"V ました／ませんでした", dec:["に"],
    err:["きのうかえります。","きのうかえりました。","Com きのう, o verbo vai obrigatoriamente para ました／ませんでした."],
    s:["わたし:S は:A きのう:D かえりました:V | Eu voltei para casa ontem. | かえります",
       "ミラーさん:S は:A きのう:D べんきょうしました:V | O Sr. Miller estudou ontem. | べんきょうします",
       "わたし:S は:A きのう:D やすみました:V | Eu descansei ontem. | やすみます",
       "わたし:S は:A きのう:D はたらきませんでした:V | Eu não trabalhei ontem. | はたらきません"]},
  { k:"C", name:"Horário com に", f:"N(tempo) に V", dec:["で","を"],
    err:["わたしはきのうにかえりました。","わたしはきのうかえりました。","Horas específicas = に; tempos relativos (きのう、まいにち) ficam sem に."],
    s:["わたし:S は:A 7じ:D に:A おきます:V | Eu acordo às 7 horas.",
       "ミラーさん:S は:A 5じ:D に:A かえります:V | O Sr. Miller volta para casa às 5 horas.",
       "わたし:S は:A 8じ:D に:A べんきょうします:V | Eu estudo às 8 horas.",
       "ミラーさん:S は:A 11じ:D に:A ねます:V | O Sr. Miller dorme às 11 horas."]}
  ]},
{ n:6, t:"きのうはどこへいきましたか",
  obj:["Indicar direção com へ","Marcar objeto direto com を","Indicar meio de transporte com で"],
  pts:[
  { k:"A", name:"Direção com へ", f:"N(lugar) へ いきます／きます／かえります", dec:["を","で"],
    err:["かえりましたうちへ。","うちへかえりました。","O verbo de movimento fecha a oração: destino + へ + verbo."],
    s:["わたし:S は:A きのう:D うち:O へ:A かえりました:V | Ontem eu voltei para casa.",
       "ミラーさん:S は:A おととい:D にほん:O へ:A いきました:V | Anteontem o Sr. Miller foi ao Japão.",
       "ともだち:S は:A わたしのうち:O へ:A きました:V | Um amigo veio à minha casa.",
       "ミラーさん:S は:A 5じ:D に:A うち:O へ:A かえりました:V | O Sr. Miller voltou para casa às 5 horas."]},
  { k:"B", name:"Objeto direto com を", f:"N を V", dec:["が","へ"],
    err:["パンがたべました。","パンをたべました。","が marca o sujeito; o objeto direto sempre leva を."],
    s:["わたし:S は:A きのう:D パン:O を:A たべました:V | Ontem eu comi pão.",
       "ミラーさん:S は:A みず:O を:A のみました:V | O Sr. Miller bebeu água.",
       "ミラーさん:S は:A きのう:D しゃしん:O を:A みました:V | Ontem o Sr. Miller viu as fotos.",
       "わたし:S は:A てがみ:O を:A かきました:V | Eu escrevi uma carta."]},
  { k:"C", name:"Transporte com で", f:"N(meio) で V", dec:["に","を"],
    err:["バスにいきました。","バスでいきました。","に marca destino; o meio de transporte sempre leva で."],
    s:["わたし:S は:A バス:D で:A うち:O へ:A かえりました:V | Eu voltei para casa de ônibus.",
       "ミラーさん:S は:A でんしゃ:D で:A かいしゃ:O へ:A いきました:V | O Sr. Miller foi à empresa de trem.",
       "わたし:S は:A じてんしゃ:D で:A だいがく:O へ:A いきました:V | Eu fui à universidade de bicicleta.",
       "ミラーさん:S は:A タクシー:D で:A うち:O へ:A かえりました:V | O Sr. Miller voltou para casa de táxi."]}
  ]},
{ n:7, t:"ミラーさんはふみをもらいました",
  obj:["Usar で para ferramenta e idioma","Diferenciar あげます／もらいます com に","Perguntar com もう〜ました e responder まだです"],
  pts:[
  { k:"A", name:"Ferramenta e idioma com で", f:"N(ferramenta／língua) で V", dec:["に","が","へ"],
    err:["わたしははしをごはんをたべます。","わたしははしでごはんをたべます。","を é do objeto direto; a ferramenta ou meio sempre leva で."],
    s:["わたし:S は:A はし:D で:A ごはん:O を:A たべます:V | Eu como arroz com hashi.",
       "ミラーさん:S は:A パソコン:D で:A レポート:O を:A かきます:V | O Sr. Miller escreve o relatório no computador.",
       "わたし:S は:A はさみ:D で:A かみ:O を:A きります:V | Eu corto papel com tesoura.",
       "ミラーさん:S は:A にほんご:D で:A てがみ:O を:A かきます:V | O Sr. Miller escreve cartas em japonês."]},
  { k:"B", name:"あげます／もらいます", f:"〈人〉に N を あげます／もらいます", dec:["が","で"],
    err:["わたしはともだちをプレゼントをあげました。","わたしはともだちにプレゼントをあげました。","A pessoa envolvida (quem dá ou recebe) leva に."],
    s:["わたし:S は:A ともだち:D に:A はな:O を:A あげました:V | Eu dei flores a um amigo.",
       "わたし:S は:A かのじょ:D に:A プレゼント:O を:A もらいました:V | Eu ganhei um presente da minha namorada.",
       "ミラーさん:S は:A ともだち:D に:A おかね:O を:A かしました:V | O Sr. Miller emprestou dinheiro a um amigo.",
       "わたし:S は:A せんせい:D に:A にほんご:O を:A ならいます:V | Eu aprendo japonês com o professor."]},
  { k:"C", name:"もう〜ました／まだです", f:"もう Vましたか → いいえ、まだです", dec:["を"],
    err:["いいえ、もうたべませんでした。","いいえ、まだです。","もう não combina com negativo; para \"ainda não\", use まだです."],
    s:["もう:D ひるごはん:O を:A たべました:V か:A | Você já almoçou? | まだ:D",
       "もう:D とうきょうタワー:O へ:A いきました:V か:A | Você já foi à Torre de Tóquio? | まだ:D",
       "いいえ、:D まだ:D です:V | Não, ainda não. | もう:D, ませんでした:V",
       "はい、:D もう:D しゅくだい:O を:A しました:V | Sim, já fiz a lição de casa. | まだ:D"]}
  ]},
{ n:8, t:"そのりょかんはやすくないです",
  obj:["Negar adjetivos イ (くないです) e ナ (じゃありません)","Ligar adjetivos a substantivos","Usar a forma irregular いい → よくないです"],
  pts:[
  { k:"A", name:"Negativo イ: ～くないです", f:"N は イadj くないです", dec:["じゃありません:V"],
    err:["このりょかんはやすいじゃありません。","このりょかんはやすくないです。","A negação de イadjetivos é くないです; じゃありません é só para ナadj e substantivos."],
    s:["このりょかん:S は:A やすくない:O です:V | Esta pousada não é barata. | やすい",
       "そのビル:S は:A たかくない:O です:V | Esse prédio não é alto. | たかい",
       "このへや:S は:A おおきくない:O です:V | Este quarto não é grande. | おおきい",
       "きょうのてんき:S は:A よくない:O です:V | O tempo hoje não está bom. | いくない"]},
  { k:"B", name:"Negativo ナ: ～じゃありません", f:"N は ナadj じゃありません", dec:["くないです","な"],
    err:["このへやはしずかくないです。","このへやはしずかじゃありません。","Adjetivos ナ não flexionam: a negação é sempre じゃありません."],
    s:["このへや:S は:A しずか:O じゃありません:V | Este quarto não é silencioso.",
       "このえき:S は:A にぎやか:O じゃありません:V | Esta estação não é movimentada.",
       "このビル:S は:A きれい:O じゃありません:V | Este prédio não é bonito.",
       "このりょかん:S は:A ゆうめい:O じゃありません:V | Esta pousada não é famosa."]},
  { k:"C", name:"Adjetivo + substantivo", f:"イadj + N ／ ナadj + な + N", dec:["な","の"],
    err:["これはきれいへやです。","これはきれいなへやです。","ナadjetivos exigem な antes do substantivo; イadjetivos ligam-se direto."],
    s:["わたし:S は:A きのう:D おもしろい:O ほん:O を:A かいました:V | Ontem eu comprei um livro interessante.",
       "これ:S は:A きれい:O な:A はな:O です:V | Isto é uma flor bonita.",
       "ミラーさん:S は:A きれい:O な:A しゃしん:O を:A とりました:V | O Sr. Miller tirou uma foto bonita.",
       "わたし:S は:A おもしろい:O ざっし:O を:A よみました:V | Eu li uma revista interessante."]}
  ]},
{ n:9, t:"わたしはイタリアりょうりがすきです",
  obj:["Expressar gostos com 〜は〜がすきです","Falar de habilidade com 〜がわかります","Dar razões com 〜から"],
  pts:[
  { k:"A", name:"Gostos: 〜がすきです", f:"N1 は N2 が すきです", dec:["を","に"],
    err:["わたしはサッカーをすきです。","わたしはサッカーがすきです。","すき/きらい/じょうず marcam o objeto com が, nunca com を."],
    s:["わたし:S は:A サッカー:O が:A すきです:V | Eu gosto de futebol.",
       "カリナさん:S は:A え:O が:A じょうずです:V | A Karina desenha muito bem.",
       "ミラーさん:S は:A スポーツ:O が:A とても:D すきです:V | O Sr. Miller gosta muito de esportes.",
       "わたし:S は:A おさけ:O が:A きらいです:V | Eu detesto bebida alcoólica."]},
  { k:"B", name:"Habilidade: 〜がわかります", f:"N1 は N2 が わかります", dec:["を","で"],
    err:["わたしはにほんごをわかります。","わたしはにほんごがわかります。","わかります／あります seguem o padrão が, como すきです."],
    s:["わたし:S は:A にほんご:O が:A すこし:D わかります:V | Eu entendo um pouco de japonês.",
       "ミラーさん:S は:A えいご:O が:A わかります:V | O Sr. Miller entende inglês.",
       "ミラーさん:S は:A かんじ:O が:A ぜんぜん:D わかりません:V | O Sr. Miller não entende nada de kanji.",
       "わたし:S は:A くるま:O が:A あります:V | Eu tenho carro."]},
  { k:"C", name:"Razão: 〜から", f:"S1 から、S2", dec:["を","まで"],
    err:["きょうはこどものたんじょうびです、はやくかえります。","きょうはこどものたんじょうびですから、はやくかえります。","から é o conector que une causa e efeito; a razão vem antes."],
    s:["きょう:S は:A こどものたんじょうびです:O から、:A はやく:D かえります:V | Hoje é aniversário do meu filho, então vou voltar cedo.",
       "きょう:S は:A にちようびです:O から、:A かいしゃ:O へ:A いきません:V | Hoje é domingo, então não vou à empresa.",
       "ようじ:O が:A ありました:V から、:A はやく:D かえりました:V | Eu tinha um compromisso, por isso voltei cedo.",
       "おさけ:O は:A あまりすきじゃありません:V から、:A のみません:V | Não gosto muito de álcool, por isso não bebo."]}
  ]},
{ n:10, t:"あそこにコンビニがあります",
  obj:["Existência: あります (coisas) e います (pessoas/animais)","Posição: N1 の まえ／うしろ／なか…に","Localização: N は 場所 に あります"],
  pts:[
  { k:"A", name:"〈場所〉に N が あります／います", f:"場所 に N が あります／います", dec:["を"],
    err:["あそこにコンビニをあります。","あそこにコンビニがあります。","A coisa ou pessoa que existe leva が. あります = coisas; います = seres vivos."],
    s:["あそこ:D に:A コンビニ:O が:A あります:V | Ali tem uma loja de conveniência. | を, います",
       "ロビー:D に:A さとうさん:O が:A います:V | A Sra. Sato está no saguão. | を, あります",
       "このビル:D に:A ATM:O が:A あります:V | Tem um caixa eletrônico neste prédio. | を, います",
       "にわ:D に:A ねこ:O が:A います:V | Tem um gato no jardim. | を, あります"]},
  { k:"B", name:"Posição: N1 の〈位置〉に", f:"N1 の まえ／した／なか に N2 が あります", dec:["で","を"],
    err:["えきまえにゆうびんきょくがあります。","えきのまえにゆうびんきょくがあります。","As palavras de posição ligam-se ao ponto de referência com の."],
    s:["えき:D の:A まえ:D に:A ぎんこう:O が:A あります:V | Tem um banco em frente à estação.",
       "ぎんこう:D の:A となり:D に:A ゆうびんきょく:O が:A あります:V | Ao lado do banco tem um correio.",
       "つくえ:D の:A した:D に:A ねこ:O が:A います:V | Embaixo da mesa tem um gato.",
       "はこ:D の:A なか:D に:A なに:O が:A あります:V か:A | O que tem dentro da caixa?"]},
  { k:"C", name:"N は 場所 に あります／います", f:"N1 は N2(lugar) に あります／います", dec:["が","を"],
    err:["かぞくはニューヨークがいます。","かぞくはニューヨークにいます。","Com o tópico は, o lugar é marcado por に."],
    s:["ミラーさん:S は:A かいぎしつ:D に:A います:V | O Sr. Miller está na sala de reuniões.",
       "ゆうびんきょく:S は:A どこ:D に:A あります:V か:A | Onde fica o correio?",
       "かぞく:S は:A ニューヨーク:D に:A います:V | Minha família está em Nova York.",
       "とうきょうディズニーランド:S は:A ちばけん:D に:A あります:V | A Tokyo Disneyland fica em Chiba."]}
  ]},
{ n:11, t:"かいぎしつにテーブルが7つあります",
  obj:["Contar com 〜つ、〜にん、〜まい、〜だい","Frequência com 期間に〜かい","Duração com 〜から〜まで かかります"],
  pts:[
  { k:"A", name:"Contadores 〜つ e 〜にん", f:"N が 数+つ／にん あります／います", dec:["を"],
    err:["こどもが2ついます。","こどもが2にんいます。","つ é para coisas; pessoas exigem 〜にん (ひとり、ふたり)."],
    s:["かいぎしつ:D に:A テーブル:O が:A 7つ:D あります:V | Na sala de reuniões há 7 mesas. | 7にん",
       "きょうしつ:D に:A がくせい:O が:A 3にん:D います:V | Há 3 alunos na sala de aula. | 3つ",
       "わたし:S は:A りんご:O を:A 4つ:D かいました:V | Eu comprei 4 maçãs. | 4まい",
       "わたし:S は:A こども:O が:A ふたり:D います:V | Eu tenho dois filhos. | 2つ:D"]},
  { k:"B", name:"Contadores 〜まい e 〜だい", f:"N を 数+まい／だい V", dec:[],
    err:["きってを5まいあります。","きってが5まいあります。","Cada objeto tem seu contador: まい (planos), だい (máquinas), つ (genérico)."],
    s:["80えん:D の:A きって:O を:A 5まい:D ください:V | Me dê 5 selos de 80 ienes, por favor. | 5だい",
       "わたし:S は:A はがき:O を:A 2まい:D かいました:V | Eu comprei 2 cartões-postais. | 2だい",
       "うち:D に:A くるま:O が:A 2だい:D あります:V | Em casa há 2 carros. | 2まい",
       "わたし:S は:A しゃしん:O を:A 10まい:D とりました:V | Eu tirei 10 fotos. | 10だい"]},
  { k:"C", name:"Frequência e duração", f:"期間 に 〜かい／A から B まで かかります", dec:["で","へ"],
    err:["しゅうかん2かいテニスをします。","1しゅうかんに2かいテニスをします。","期間に〜かい é a estrutura fixa: o período leva に."],
    s:["わたし:S は:A 1しゅうかん:D に:A 2かい:D テニス:O を:A します:V | Eu jogo tênis 2 vezes por semana.",
       "わたし:S は:A 1かげつ:D に:A 3かい:D えいが:O を:A みます:V | Eu vejo filmes 3 vezes por mês.",
       "おおさか:D から:A とうきょう:D まで:A 3じかん:D かかります:V | De Osaka até Tóquio leva 3 horas.",
       "うち:D から:A がっこう:D まで:A 30ぷん:D かかります:V | De casa até a escola leva 30 minutos."]}
  ]},
{ n:12, t:"きのうはあめでした",
  obj:["Passado de substantivos e ナadj (でした)","Passado de イadj (かったです)","Comparar com より、どちらが、いちばん"],
  pts:[
  { k:"A", name:"Passado: 〜でした", f:"N・ナadj は 〜でした／じゃありませんでした", dec:["です"],
    err:["きのうはあめです。","きのうはあめでした。","Com きのう／おととい, です vira でした."],
    s:["きのう:S は:A あめ:O でした:V | Ontem choveu.",
       "おととい:S は:A にちようび:O でした:V | Anteontem foi domingo.",
       "きのうのパーティー:S は:A にぎやか:O でした:V | A festa de ontem estava animada.",
       "きのうのしけん:S は:A かんたん:O じゃありませんでした:V | A prova de ontem não foi fácil. | じゃありません"]},
  { k:"B", name:"Passado イadj: 〜かったです", f:"イadj かったです／くなかったです", dec:["でした:V"],
    err:["このほんはおもしろいでした。","このほんはおもしろかったです。","O passado do イadj é かったです; でした é só para substantivos e ナadj."],
    s:["きのうのえいが:S は:A おもしろかった:O です:V | O filme de ontem foi interessante. | おもしろい, でした",
       "りょこう:S は:A たのしかった:O です:V | A viagem foi divertida. | たのしい, でした",
       "そのりょかん:S は:A やすくなかった:O です:V | Aquela pousada não foi barata. | やすくない, でした",
       "きのうのてんき:S は:A よかった:O です:V | O tempo ontem estava bom. | いかった, でした"]},
  { k:"C", name:"より／どちらが／いちばん", f:"A は B より adj です", dec:["が","の"],
    err:["ほっかいどうはきゅうしゅうがおおきいです。","ほっかいどうはきゅうしゅうよりおおきいです。","Na comparação \"mais do que\", o termo comparado leva より."],
    s:["ほっかいどう:S は:A きゅうしゅう:D より:A おおきい:O です:V | Hokkaido é maior que Kyushu.",
       "サッカー:S と:A テニス:S と:A どちら:D が:A おもしろい:O です:V か:A | O que é mais interessante, futebol ou tênis? | より",
       "サッカー:S の:A ほう:S が:A おもしろい:O です:V | Futebol é mais interessante. | より",
       "1ねん:D で:A なつ:O が:A いちばん:D すきです:V | Do ano todo, gosto mais do verão. | より, に"]}
  ]},
{ n:13, t:"わたしはくるまがほしいです",
  obj:["Desejo de posse com 〜がほしいです","Desejo de ação com Vたいです","Propósito com 〜へ Vに いきます"],
  pts:[
  { k:"A", name:"〜がほしいです", f:"わたしは N が ほしいです", dec:["を","に"],
    err:["わたしはくるまをほしいです。","わたしはくるまがほしいです。","ほしい é イadjetivo; seu objeto leva が."],
    s:["わたし:S は:A くるま:O が:A ほしいです:V | Eu quero um carro.",
       "わたし:S は:A あたらしい:O パソコン:O が:A ほしいです:V | Eu quero um computador novo.",
       "わたし:S は:A ふるい:O くるま:O が:A ほしくないです:V | Eu não quero um carro velho.",
       "いま:D なに:O が:A いちばん:D ほしいです:V か:A | O que você mais quer agora?"]},
  { k:"B", name:"Desejo de ação: Vたいです", f:"V(ます形) + たいです", dec:[],
    err:["わたしはにほんへいきますたいです。","わたしはにほんへいきたいです。","たい substitui ます: いきます → いきたい."],
    s:["わたし:S は:A にほん:O へ:A いきたいです:V | Eu quero ir ao Japão. | いきますたいです",
       "わたし:S は:A すし:O を:A たべたいです:V | Eu quero comer sushi. | たべますたいです",
       "わたし:S は:A ともだち:O に:A あいたいです:V | Eu quero encontrar meus amigos. | あいますたいです",
       "きょう:S は:A うち:O へ:A かえりたくないです:V | Hoje não quero voltar para casa. | かえりたいないです"]},
  { k:"C", name:"Propósito: 〜に いきます", f:"場所 へ V(ます形) に いきます", dec:["を"],
    err:["にほんへにほんごをならいますにいきます。","にほんへにほんごをならいにいきます。","O propósito usa o ます形 sem ます + に."],
    s:["わたし:S は:A にほん:O へ:A にほんご:O を:A ならい:V に:A いきます:V | Eu vou ao Japão estudar japonês. | ならいます",
       "わたし:S は:A デパート:O へ:A かいもの:O に:A いきます:V | Eu vou à loja de departamentos fazer compras. | で",
       "ミラーさん:S は:A とうきょう:O へ:A しごと:O に:A きました:V | O Sr. Miller veio a Tóquio a trabalho. | で",
       "わたし:S は:A きっさてん:O へ:A コーヒー:O を:A のみ:V に:A いきます:V | Eu vou à cafeteria tomar café. | のみます"]}
  ]},
{ n:14, t:"ちょっとまってください",
  obj:["Conjugar a forma て (grupos I, II e III)","Pedir com 〜てください","Ação em andamento com 〜ています"],
  pts:[
  { k:"A", name:"Forma て", f:"かきます→かいて／まちます→まって／きます→きて", dec:[],
    err:["かきます → かきて","かきます → かいて","O grupo I tem regras próprias: って／んで／いて／して."],
    s:["ここ:D に:A なまえ:O を:A かいて:V ください:A | Escreva seu nome aqui, por favor. | かきて",
       "あした:D また:D きて:V ください:A | Venha de novo amanhã, por favor. | こて",
       "パン:O を:A かって:V ください:A | Compre pão, por favor. | かうて",
       "ゆっくり:D はなして:V ください:A | Fale devagar, por favor. | はなって"]},
  { k:"B", name:"Pedidos: 〜てください", f:"Vて ください", dec:[],
    err:["ちょっとまちてください。","ちょっとまってください。","まちます → まって. Revise as regras do grupo I."],
    s:["ちょっと:D まって:V ください:A | Espere um pouco, por favor. | まちて",
       "これ:O を:A みせて:V ください:A | Mostre isto, por favor. | みせって",
       "このほん:O を:A よんで:V ください:A | Leia este livro, por favor. | よみて",
       "どうぞ:D このケーキ:O を:A たべて:V ください:A | Fique à vontade, coma este bolo. | たべって"]},
  { k:"C", name:"Em andamento: 〜ています", f:"Vて います", dec:[],
    err:["ミラーさんはいまでんわをかけます。","ミラーさんはいまでんわをかけています。","Com いま e ação em progresso, use 〜ています."],
    s:["ミラーさん:S は:A いま:D でんわ:O を:A かけています:V | O Sr. Miller está telefonando agora. | かけます",
       "ミラーさん:S は:A かいぎしつ:D で:A まつもとさん:O と:A はなしています:V | O Sr. Miller está conversando com o Sr. Matsumoto na sala de reuniões. | はなします",
       "わたし:S は:A いま:D にほんご:O を:A べんきょうしています:V | Eu estou estudando japonês agora. | べんきょうします",
       "いま:D あめ:S が:A ふっています:V | Está chovendo agora. | ふります"]}
  ]},
{ n:15, t:"ここでしゃしんをとってはいけません",
  obj:["Pedir permissão com 〜てもいいですか","Proibir com 〜てはいけません","Estados com 〜ています (casado, ter, saber, morar)"],
  pts:[
  { k:"A", name:"Permissão: 〜てもいいですか", f:"Vて もいいですか", dec:["はいけません:A"],
    err:["ここにすわりますもいいですか。","ここにすわってもいいですか。","A permissão exige a forma て antes de もいいですか."],
    s:["ここ:D に:A すわって:V もいいですか:A | Posso me sentar aqui? | すわります",
       "このほん:O を:A みて:V もいいですか:A | Posso ver este livro? | みます",
       "ここ:D で:A しゃしん:O を:A とって:V もいいですか:A | Posso tirar fotos aqui? | とります",
       "パソコン:O を:A つかって:V もいいですか:A | Posso usar o computador? | つかいます"]},
  { k:"B", name:"Proibição: 〜てはいけません", f:"Vて はいけません", dec:["もいいません:A","もいいですか:A"],
    err:["ここでしゃしんをとってもいいません。","ここでしゃしんをとってはいけません。","てもいいですか pergunta; てはいけません proíbe. \"てもいいません\" não existe."],
    s:["ここ:D で:A しゃしん:O を:A とって:V はいけません:A | Não é permitido tirar fotos aqui.",
       "ここ:D で:A たばこ:O を:A すって:V はいけません:A | Não pode fumar aqui.",
       "このへや:D に:A はいって:V はいけません:A | Não pode entrar nesta sala.",
       "としょかん:D で:A ケータイ:O を:A つかって:V はいけません:A | Não pode usar o celular na biblioteca."]},
  { k:"C", name:"Estados com 〜ています", f:"Vて います (estado)", dec:[],
    err:["わたしはけっこんします。","わたしはけっこんしています。","Estados (casado, ter, saber, morar) usam 〜ています."],
    s:["わたし:S は:A けっこんしています:V | Eu sou casado(a). | けっこんします",
       "ミラーさん:S は:A くるま:O を:A もっています:V | O Sr. Miller tem carro. | もちます",
       "わたし:S は:A ミラーさん:O の:A でんわばんごう:O を:A しっています:V | Eu sei o telefone do Sr. Miller. | しります",
       "わたし:S は:A とうきょう:O に:A すんでいます:V | Eu moro em Tóquio. | すみます, で"]}
  ]},
{ n:16, t:"かいものをして、うちへかえりました",
  obj:["Ações em sequência com V1てV2","Ordem temporal com 〜てから","Razão com イadjくて／ナadj・Nで"],
  pts:[
  { k:"A", name:"Sequência: V1て V2", f:"V1て、V2て、V3", dec:[],
    err:["かいものをしました、うちへかえりました。","かいものをして、うちへかえりました。","Só o último verbo carrega o tempo; os anteriores ficam em て形."],
    s:["わたし:S は:A かいもの:O を:A して、:V うち:O へ:A かえりました:V | Eu fiz compras e voltei para casa. | しました、",
       "ミラーさん:S は:A あさごはん:O を:A たべて、:V かいしゃ:O へ:A いきました:V | O Sr. Miller tomou café da manhã e foi para a empresa. | たべました、",
       "あさ:D シャワー:O を:A あびて、:V かいしゃ:O へ:A いきます:V | De manhã eu tomo banho e vou para a empresa. | あびます、",
       "きのう:D ともだち:O に:A あって、:V えいが:O を:A みました:V | Ontem encontrei um amigo e vi um filme. | あいました、"]},
  { k:"B", name:"Depois de: 〜てから", f:"V1てから V2", dec:[],
    err:["しごとをしますから、かえりました。","しごとをしてから、かえりました。","Ordem temporal exige てから; から sozinho dá razão."],
    s:["わたし:S は:A しゅくだい:O を:A して:V から、:A ねました:V | Eu dormi depois de fazer a lição de casa. | します:V",
       "しごと:O が:A おわって:V から、:A うち:O へ:A かえりました:V | Voltei para casa depois que o trabalho terminou. | おわります",
       "ごはん:O を:A たべて:V から、:A そうじ:O を:A しました:V | Depois de comer, fiz a faxina. | たべます",
       "てがみ:O を:A かいて:V から、:A ねます:V | Vou dormir depois de escrever a carta. | かきます"]},
  { k:"C", name:"Razão: 〜くて／〜で", f:"イadj→くて／ナadj・N→で", dec:[],
    err:["あついで、のどがかわきました。","あつくて、のどがかわきました。","イadj ligam-se com くて; で é para ナadj e substantivos."],
    s:["あつくて、:O のど:S が:A かわきました:V | Estava calor e fiquei com sede. | あついで、",
       "あたま:S が:A いたくて、:O かいしゃ:O を:A やすみました:V | Minha cabeça doía, então faltei ao trabalho. | いたいで、",
       "ミラーさん:S は:A ハンサムで、:O しんせつ:O です:V | O Sr. Miller é bonito e gentil. | ハンサムくて、",
       "このへや:S は:A ひろくて、:O あかるい:O です:V | Este quarto é espaçoso e claro. | ひろいで、"]}
  ]},
{ n:17, t:"あまりむりをしないでください",
  obj:["Pedido negativo com 〜ないでください","Obrigação com 〜なければなりません","Sem obrigação com 〜なくてもいいです"],
  pts:[
  { k:"A", name:"〜ないでください", f:"Vない形 + でください", dec:[],
    err:["ここでしゃしんをとらなくてください。","ここでしゃしんをとらないでください。","O pedido negativo usa ないでください."],
    s:["ここ:D で:A しゃしん:O を:A とらないで:V ください:A | Por favor, não tire fotos aqui. | とらなくて",
       "わたし:S の:A にっき:O を:A みないで:V ください:A | Por favor, não leia o meu diário. | みなくて",
       "このへや:D に:A はいらないで:V ください:A | Por favor, não entre nesta sala. | はいらなくて",
       "あまり:D むり:O を:A しないで:V ください:A | Não se esforce demais, por favor. | しなくて"]},
  { k:"B", name:"Obrigação: 〜なければなりません", f:"Vない → なければなりません", dec:[],
    err:["かぜですから、くすりをのまなくてもいいです。","かぜですから、くすりをのまなければなりません。","なくてもいいです (não precisa) e なければなりません (precisa) são opostos."],
    s:["わたし:S は:A しゅくだい:O を:A しなければなりません:V | Eu preciso fazer a lição de casa. | しなくてもいいです",
       "ミラーさん:S は:A かいぎ:O に:A でなければなりません:V | O Sr. Miller precisa participar da reunião. | でなくてもいいです",
       "わたし:S は:A まいあさ:D 6じ:D に:A おきなければなりません:V | Eu preciso acordar às 6 horas todas as manhãs. | おきなくてもいいです",
       "かぜ:O です:V から、:A くすり:O を:A のまなければなりません:V | Estou resfriado, então preciso tomar remédio. | のまなくてもいいです"]},
  { k:"C", name:"Sem obrigação: 〜なくてもいいです", f:"Vない → なくてもいいです", dec:[],
    err:["ここでけいたいでんわをつかわなくてもいいです。(proibição)","ここでけいたいでんわをつかわないでください。","なくてもいいです libera a ação; para proibir, use ないでください."],
    s:["あした:D は:A こなくてもいいです:V | Amanhã você não precisa vir. | こなければなりません",
       "くつ:O を:A ぬがなくてもいいです:V | Não precisa tirar os sapatos. | ぬがないでください",
       "しんぶん:O を:A かわなくてもいいです:V | Não precisa comprar o jornal. | かわなければなりません",
       "きょう:D は:A ざんぎょう:O を:A しなくてもいいです:V | Hoje você não precisa fazer hora extra. | しないでください"]}
  ]},
{ n:18, t:"わたしのしゅみはスポーツです",
  obj:["Habilidade e possibilidade com 〜ことができます","Hobbies com 〜ことです","Antes de: 〜まえに"],
  pts:[
  { k:"A", name:"〜ことができます", f:"V(辞書形) + ことができます", dec:[],
    err:["わたしはにほんごがはなしますことができます。","わたしはにほんごをはなすことができます。","A estrutura exige o 辞書形 (はなす), não はなします."],
    s:["わたし:S は:A にほんご:O を:A はなす:V ことができます:A | Eu sei falar japonês. | はなします",
       "ミラーさん:S は:A ピアノ:O を:A ひく:V ことができます:A | O Sr. Miller sabe tocar piano. | ひきます:V",
       "ここ:D で:A コピー:O を:A する:V ことができます:A | Aqui é possível tirar cópias. | します:V",
       "カード:D で:A はらう:V ことができます:A | É possível pagar com cartão. | はらいます"]},
  { k:"B", name:"Hobbies: 〜ことです", f:"しゅみ は V(辞書形) こと です", dec:[],
    err:["わたしのしゅみはしゃしんをとりますことです。","わたしのしゅみはしゃしんをとることです。","O verbo antes de こと vai no 辞書形."],
    s:["わたし:S の:A しゅみ:S は:A スポーツ:O です:V | Meu hobby é esporte. | こと",
       "わたし:S の:A しゅみ:S は:A しゃしん:O を:A とる:V こと:A です:V | Meu hobby é tirar fotos. | とります",
       "ミラーさん:S の:A しゅみ:S は:A おんがく:O を:A きく:V こと:A です:V | O hobby do Sr. Miller é ouvir música. | ききます",
       "カリナさん:S の:A しゅみ:S は:A え:O を:A かく:V こと:A です:V | O hobby da Karina é desenhar. | かきます"]},
  { k:"C", name:"Antes de: 〜まえに", f:"V(辞書形)／Nの + まえに", dec:[],
    err:["ねましたまえに、ほんをよみました。","ねるまえに、ほんをよみました。","まえに exige sempre o 辞書形, mesmo em frase no passado."],
    s:["わたし:S は:A ねる:V まえに、:A ほん:O を:A よみます:V | Eu leio um livro antes de dormir. | ねます",
       "ごはん:O を:A たべる:V まえに、:A て:O を:A あらいます:V | Lavo as mãos antes de comer. | たべます",
       "しごと:O の:A まえに、:A うんどう:O を:A します:V | Faço exercício antes do trabalho. | が",
       "3ねん:D まえに、:A にほん:O へ:A きました:V | Vim ao Japão há 3 anos. | の"]}
  ]},
{ n:19, t:"うなぎをたべたことがあります",
  obj:["Experiências com 〜たことがあります","Exemplos de ações com 〜たり〜たりします","Mudança com 〜くなります／〜になります"],
  pts:[
  { k:"A", name:"〜たことがあります", f:"V(た形) + ことがあります", dec:[],
    err:["わたしはにほんへいきましたことがあります。","わたしはにほんへいったことがあります。","A experiência pede o た形 (いった), não いきました."],
    s:["わたし:S は:A にほん:O へ:A いった:V ことがあります:A | Eu já fui ao Japão. | いきました",
       "わたし:S は:A うなぎ:O を:A たべた:V ことがありません:A | Eu nunca comi enguia. | たべます",
       "カリナさん:S は:A かぶき:O を:A みた:V ことがあります:A | A Karina já assistiu kabuki. | みました",
       "ミラーさん:S は:A しんかんせん:O に:A のった:V ことがあります:A | O Sr. Miller já andou de trem-bala. | のりました"]},
  { k:"B", name:"〜たり〜たりします", f:"V1たり V2たり します", dec:[],
    err:["かいものをしたり、えいがをみます。","かいものをしたり、えいがをみたりします。","Todos os verbos exemplificados ficam em たり; o tempo vai em します."],
    s:["やすみのひ:D は:A かいもの:O を:A したり、:V えいが:O を:A みたり:V します:V | Nos dias de folga, eu faço compras, vejo filmes etc. | みます",
       "パーティー:D で:A うたったり、:V おどったり:V しました:V | Na festa, cantamos, dançamos etc. | おどります",
       "にちようび:D は:A そうじ:O を:A したり、:V せんたく:O を:A したり:V します:V | Aos domingos eu faço faxina, lavo roupa etc. | して、",
       "よる:D は:A テレビ:O を:A みたり、:V ほん:O を:A よんだり:V します:V | À noite eu vejo TV, leio livros etc. | よみます"]},
  { k:"C", name:"〜くなります／〜になります", f:"イadj→くなります／ナadj・N→になります", dec:[],
    err:["てんきがよいなりました。","てんきがよくなりました。","イadj exigem く; に なります é para ナadj e substantivos."],
    s:["てんき:S が:A よく:O なりました:V | O tempo melhorou. | いく",
       "このまち:S は:A にぎやか:O に:A なりました:V | Esta cidade ficou movimentada. | く",
       "ミラーさん:S は:A らいねん:D せんせい:O に:A なります:V | O Sr. Miller vai se tornar professor no ano que vem. | く",
       "だんだん:D さむく:O なりました:V | Foi ficando cada vez mais frio. | さむいに"]}
  ]},
{ n:20, t:"かぜをひいたんです",
  obj:["Verbos no 普通形 (forma informal)","Adjetivos e substantivos no 普通形","Explicar com 〜のです／んです"],
  pts:[
  { k:"A", name:"Verbos no 普通形", f:"いく／いかない／いった／いかなかった", dec:[],
    err:["みます → みるでした","みます → みた","O passado do 普通形 é o た形, não 辞書形 + でした."],
    s:["あした:D きょうと:O へ:A いく:V | Amanhã vou a Kyoto. (informal) | いくです",
       "きのう:D えいが:O を:A みた:V | Ontem eu vi um filme. (informal) | みるでした",
       "きょう:D は:A がっこう:O へ:A いかない:V | Hoje não vou à escola. (informal) | いかないです",
       "ゆうべ:D は:A ばんごはん:O を:A たべなかった:V | Ontem à noite não jantei. (informal) | たべないでした"]},
  { k:"B", name:"Adjetivos e N no 普通形", f:"やすい／しずかだ／がくせいだった", dec:[],
    err:["このへやはしずかだです。","このへやはしずかだ。","だ (常体) e です (丁寧体) não se combinam na mesma frase."],
    s:["このほん:S は:A おもしろい:O | Este livro é interessante. (informal) | だ",
       "このへや:S は:A しずか:O だ:V | Este quarto é silencioso. (informal) | です",
       "ミラーさん:S は:A がくせい:O じゃない:V | O Sr. Miller não é estudante. (informal) | くない",
       "きのうのパーティー:S は:A おもしろくなかった:O | A festa de ontem não foi divertida. (informal) | おもしろいじゃなかった"]},
  { k:"C", name:"Explicação: 〜んです", f:"普通形 + んです (ナadj・N + な)", dec:[],
    err:["あしたしけんがありますのです。","あしたしけんがあるのです。","のです／んです segue o 普通形, não o ます形."],
    s:["あした:D しけん:O が:A ある:V んです:A | É que amanhã tenho prova. | あります:V",
       "きのう:D かぜ:O を:A ひいた:V んです:A | É que peguei um resfriado ontem. | ひきました",
       "びょうき:O な:A んです:A | É que estou doente. | だ",
       "あたま:S が:A いたい:O んです:A | É que estou com dor de cabeça. | な"]}
  ]},
{ n:21, t:"わたしもそうおもいます",
  obj:["Opinião com 普通形 + とおもいます","Citação com 〜といいました","Suposição com 〜でしょう"],
  pts:[
  { k:"A", name:"Opinião: 〜とおもいます", f:"普通形 + と おもいます", dec:[],
    err:["わたしはあしたあめがふりますとおもいます。","わたしはあしたあめがふるとおもいます。","A oração antes de と vai no 普通形."],
    s:["あした:D あめ:S が:A ふる:V と:A おもいます:V | Acho que amanhã vai chover. | ふります",
       "かれ:S は:A こない:V と:A おもいます:V | Acho que ele não vem. | きません",
       "にほんご:S は:A おもしろい:O と:A おもいます:V | Acho que o japonês é interessante. | おもしろいです",
       "ミラーさん:S は:A もう:D かえった:V と:A おもいます:V | Acho que o Sr. Miller já foi embora. | かえりました"]},
  { k:"B", name:"Citação: 〜といいました", f:"普通形 + と いいました", dec:[],
    err:["ミラーさんは「あしたきます」といいました。(discurso indireto)","ミラーさんはあしたくるといいました。","A fala relatada vai no 普通形."],
    s:["ミラーさん:S は:A あした:D くる:V と:A いいました:V | O Sr. Miller disse que vem amanhã. | きます",
       "カリナさん:S は:A にほん:O が:A すきだ:V と:A いいました:V | A Karina disse que gosta do Japão. | すきです",
       "せんせい:S は:A しけん:O は:A やさしい:O と:A いいました:V | O professor disse que a prova é fácil. | やさしいです",
       "ミラーさん:S は:A しごと:O が:A おわらない:V と:A いっていました:V | O Sr. Miller estava dizendo que o trabalho não termina. | おわりません"]},
  { k:"C", name:"Suposição: 〜でしょう", f:"普通形 + でしょう", dec:["だ"],
    err:["このへやはおおきいだでしょう。","このへやはおおきいでしょう。","イadj ligam-se direto a でしょう; だ cai."],
    s:["あした:D は:A さむい:O でしょう:V | Amanhã deve fazer frio.",
       "きのうのパーティー:S は:A たのしかった:O でしょう:V | A festa de ontem foi divertida, não foi?",
       "ミラーさん:S も:A くる:V でしょう:A | O Sr. Miller também deve vir. | きます",
       "あした:D は:A いい:O てんき:O でしょう:V | Amanhã deve fazer tempo bom."]}
  ]},
{ n:22, t:"わたしがかったほん",
  obj:["Modificar substantivos com orações (わたしがかったほん)","Orações relativas negativas (しらないひと)","Sujeito da oração interna com が"],
  pts:[
  { k:"A", name:"Oração relativa: V + N", f:"V(普通形) + N", dec:[],
    err:["わたしがきのうかったですほん","わたしがきのうかったほん","です／ます não entram na oração modificadora."],
    s:["これ:S は:A わたし:O が:A かった:V ほん:O です:V | Este é o livro que eu comprei. | かいました",
       "たなかさん:O が:A つくった:V ケーキ:S は:A おいしい:O です:V | O bolo que o Sr. Tanaka fez é gostoso. | つくりました",
       "わたし:S は:A かれ:O が:A かいた:V え:O を:A みました:V | Eu vi o quadro que ele pintou. | かきました",
       "かいもの:O に:A いく:V じかん:O が:A ありません:V | Não tenho tempo de ir às compras. | いきます"]},
  { k:"B", name:"Relativa negativa: Vない + N", f:"V(ない形) + N", dec:[],
    err:["しらないですひとがいます。","しらないひとがいます。","O ない形 liga-se direto ao substantivo."],
    s:["ここ:D に:A しらない:V ひと:O が:A います:V | Aqui há uma pessoa que eu não conheço. | しらないです",
       "まだ:D よんでいない:V ほん:O が:A あります:V | Tenho livros que ainda não li. | よんでいません",
       "わからない:V ところ:O を:A おしえて:V ください:A | Por favor, me ensine a parte que eu não entendo. | わかりません",
       "つかわない:V パソコン:O が:A あります:V | Tenho um computador que não uso. | つかいません"]},
  { k:"C", name:"Partículas na oração relativa", f:"sujeito interno: は → が", dec:[],
    err:["わたしはかったほんがおもしろいです。","わたしがかったほんはおもしろいです。","O sujeito da oração relativa leva が; は marca o tópico da frase inteira."],
    s:["わたし:O が:A かった:V ほん:S は:A おもしろい:O です:V | O livro que eu comprei é interessante. | を",
       "にほん:O で:A かった:V カメラ:S は:A たかかった:O です:V | A câmera que comprei no Japão foi cara. | に",
       "ともだち:O に:A もらった:V ほん:O を:A なくしました:V | Perdi o livro que ganhei de um amigo. | が, で",
       "ミラーさん:O が:A すんでいた:V いえ:S は:A ふるい:O です:V | A casa onde o Sr. Miller morava é velha. | すんでいました"]}
  ]},
{ n:23, t:"ほんをかりるとき、カードがいります",
  obj:["Momento com V(辞書形／た形) + とき","イadj＋とき、ナadj＋なとき、N＋のとき","Condição natural com V + と"],
  pts:[
  { k:"A", name:"V + とき", f:"V(辞書形／た形) + とき", dec:[],
    err:["ほんをかりますとき、カードがいります。","ほんをかりるとき、カードがいります。","とき exige 普通形, nunca ます形."],
    s:["ほん:O を:A かりる:V とき、:A カード:O が:A いります:V | Para pegar um livro emprestado, precisa do cartão. | かります",
       "にほん:O に:A ついた:V とき、:A でんわ:O を:A して:V ください:A | Quando chegar ao Japão, me telefone. | つきます",
       "ともだち:S が:A くる:V とき、:A ケーキ:O を:A つくります:V | Quando meu amigo vier, vou fazer um bolo. | きます",
       "でかける:V とき、:A かぎ:O を:A かけます:V | Quando saio, tranco a porta. | でかけます"]},
  { k:"B", name:"Adj／N + とき", f:"イadj + とき／ナadj + な とき／N + の とき", dec:[],
    err:["ひまとき","ひまなとき","ナadj exigem な e substantivos exigem の antes de とき."],
    s:["ひま:O な:A とき、:A このほん:O を:A よんで:V ください:A | Quando estiver livre, leia este livro. | の",
       "あたま:S が:A いたい:O とき、:A このくすり:O を:A のんで:V ください:A | Quando estiver com dor de cabeça, tome este remédio. | な, の",
       "こども:O の:A とき、:A ブラジル:O に:A すんでいました:V | Quando era criança, eu morava no Brasil. | な",
       "ひるごはん:O の:A とき、:A テレビ:O を:A みます:V | Na hora do almoço, eu assisto TV. | な"]},
  { k:"C", name:"Condição natural: V + と", f:"V(辞書形) + と、〜", dec:[],
    err:["このみちをまっすぐいきますと、みぎにあります。","このみちをまっすぐいくと、みぎにあります。","と (condição) exige 普通形."],
    s:["このボタン:O を:A おす:V と、:A おつり:S が:A でます:V | Apertando este botão, sai o troco. | おします",
       "このみち:O を:A まっすぐ:D いく:V と、:A みぎ:D に:A えき:O が:A あります:V | Seguindo reto por esta rua, a estação fica à direita. | いきます",
       "はる:S に:A なる:V と、:A さくら:S が:A さきます:V | Quando chega a primavera, as cerejeiras florescem. | なります",
       "これ:O を:A まわす:V と、:A おと:S が:A おおきく:O なります:V | Girando isto, o som fica mais alto. | まわします"]}
  ]},
{ n:24, t:"かさをかしてくれました",
  obj:["Dar para mim com くれます","Receber favores com 〜てもらいます","Fazer favores com 〜てあげます／〜てくれます"],
  pts:[
  { k:"A", name:"Dar a mim: くれます", f:"〈人〉は（わたしに）N を くれます", dec:[],
    err:["わたしはともだちにプレゼントをくれました。","わたしはともだちにプレゼントをあげました。","くれる = direção PARA mim; saindo de mim, use あげます."],
    s:["ともだち:S が:A わたし:O に:A プレゼント:O を:A くれました:V | Um amigo me deu um presente. | あげました",
       "かのじょ:S が:A てがみ:O を:A くれました:V | Minha namorada me deu uma carta. | あげました",
       "このとけい:O は:A ちち:S が:A くれました:V | Este relógio foi meu pai que me deu. | あげました",
       "わたし:S は:A ともだち:O に:A プレゼント:O を:A あげました:V | Eu dei um presente ao meu amigo. | くれました"]},
  { k:"B", name:"Receber favor: 〜てもらいます", f:"わたしは〈人〉に Vて もらいます", dec:["くれました"],
    err:["わたしはともだちをかさをかしてもらいました。","わたしはともだちにかさをかしてもらいました。","Quem faz o favor leva に."],
    s:["わたし:S は:A ともだち:O に:A かさ:O を:A かして:V もらいました:A | Meu amigo me emprestou um guarda-chuva (recebi esse favor).",
       "わたし:S は:A せんせい:O に:A かんじ:O を:A おしえて:V もらいました:A | O professor me ensinou kanji (recebi esse favor).",
       "わたし:S は:A ともだち:O に:A しゅくだい:O を:A てつだって:V もらいました:A | Um amigo me ajudou com a lição (recebi esse favor).",
       "わたし:S は:A ミラーさん:O に:A えき:D まで:A つれていって:V もらいました:A | O Sr. Miller me levou até a estação (recebi esse favor)."]},
  { k:"C", name:"Fazer favor: 〜てあげます／〜てくれます", f:"Vて あげます (eu → outro)／Vて くれます (outro → eu)", dec:[],
    err:["ともだちはわたしにえきまでおくってあげました。","ともだちはわたしをえきまでおくってくれました。","Se o beneficiário sou eu, use くれます."],
    s:["わたし:S は:A おっと:O に:A カレー:O を:A つくって:V あげました:A | Eu fiz curry para o meu marido. | くれました",
       "ともだち:S が:A わたし:O を:A えき:D まで:A おくって:V くれました:A | Meu amigo me levou até a estação. | あげました, に",
       "かれ:S が:A わたし:O の:A にもつ:O を:A もって:V くれました:A | Ele carregou a minha bagagem para mim. | あげました",
       "わたし:S は:A おばあさん:O の:A にもつ:O を:A もって:V あげました:A | Eu carreguei a bagagem de uma senhora. | くれました"]}
  ]},
{ n:25, t:"やすかったら、かいます",
  obj:["Condição hipotética com 〜たら","〜たら para descobertas (かえったら、…)","Concessão com 〜ても／〜くても／〜でも"],
  pts:[
  { k:"A", name:"Hipótese: 〜たら", f:"V(た形)+ら／イadj かったら／ナadj・N だったら", dec:[],
    err:["やすいだったら、かいます。","やすかったら、かいます。","イadj formam たら com かった; だったら é só para ナadj e N."],
    s:["やすかったら、:O パソコン:O を:A かいます:V | Se estiver barato, vou comprar o computador. | やすいだったら、",
       "ひま:O だったら、:A いっしょに:D えいが:O を:A みませんか:V | Se estiver livre, que tal vermos um filme juntos? | かったら、",
       "じかん:O が:A あったら、:V りょこう:O に:A いきたいです:V | Se eu tiver tempo, quero viajar. | あるたら、",
       "あめ:S が:A ふったら、:V いきません:V | Se chover, não vou. | ふるたら、"]},
  { k:"B", name:"Descoberta: 〜たら", f:"V(た形)+ら、〜 (passado)", dec:[],
    err:["うちにかえると、でんわがありました。","うちにかえったら、でんわがありました。","Para um evento específico no passado (\"quando fiz X, aconteceu Y\"), use たら."],
    s:["うち:O に:A かえったら、:V でんわ:S が:A ありました:V | Quando voltei para casa, tinha uma ligação. | かえると、",
       "ドア:O を:A あけたら、:V ねこ:S が:A いました:V | Quando abri a porta, havia um gato. | あけると、",
       "えき:O に:A ついたら、:V ともだち:S が:A まっていました:V | Quando cheguei à estação, um amigo estava esperando. | つくと、",
       "くすり:O を:A のんだら、:V げんき:O に:A なりました:V | Quando tomei o remédio, fiquei bem. | のむと、"]},
  { k:"C", name:"Concessão: 〜ても", f:"Vて+も／イadj くても／ナadj・N でも", dec:[],
    err:["あめがふるても、いきます。","あめがふっても、いきます。","A concessão exige て形 + も."],
    s:["あめ:S が:A ふっても、:V いきます:V | Mesmo que chova, eu vou. | ふるても、",
       "さむくても、:O まいあさ:D ジョギング:O を:A します:V | Mesmo fazendo frio, eu corro toda manhã. | さむいでも、",
       "やすくても、:O かいません:V | Mesmo sendo barato, não vou comprar. | やすいても、",
       "どようび:O でも、:A はたらきます:V | Mesmo no sábado, eu trabalho. | くても、"]}
  ]}
];
