"""Wraps assets/pongo_world.glb into js/world-data.js (base64) so the game
works when index.html is opened directly from disk (file://), where fetch()
of local files is blocked by the browser."""
import base64, os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
data = open(os.path.join(root, "assets", "pongo_world.glb"), "rb").read()
with open(os.path.join(root, "js", "world-data.js"), "w") as f:
    f.write("// Generated by tools/embed_glb.py from assets/pongo_world.glb (built in Blender).\n")
    f.write("window.PONGO_WORLD_GLB = \"" + base64.b64encode(data).decode() + "\";\n")
print("world-data.js:", os.path.getsize(os.path.join(root, "js", "world-data.js")) // 1024, "KB")
