# Mandarim Básico I — Manual de Aulas (Método Chunk) — Odu Creative
# Conteúdo das lições 13 a 25. Formato igual ao de content_a.py.

LESSONS_B = [
 dict(n=13, t="我想买一辆车。", py="Wǒ xiǎng mǎi yí liàng chē.", pt="Quero comprar um carro.",
  obj=["Expressar desejo de fazer algo com 想 + verbo",
       "Pedir e querer coisas com 要",
       "Indicar propósito com 去 / 来 + lugar + verbo"],
  pts=[
   dict(title="Desejo: 想 + V", forma="S + 想 + V + O",
    funcao="Dizer o que se gostaria de fazer",
    modo="Afirmativo/negativo (不想); 想 é verbo auxiliar e vem antes do verbo principal",
    ex=["我|想|买|一辆车|—|Wǒ xiǎng mǎi yí liàng chē.|Quero comprar um carro.",
        "马克|想|去|中国|—|Mǎkè xiǎng qù Zhōngguó.|O Mark quer ir à China.",
        "我|今天不想|做|饭|—|Wǒ jīntiān bù xiǎng zuò fàn.|Hoje não quero cozinhar.",
        "你|想|喝|什么|—|Nǐ xiǎng hē shénme?|O que você quer beber?"],
    wrong="我买想一辆车。", right="我想买一辆车。",
    erro="Colocar 想 depois do verbo principal. Verbos auxiliares (想、会、能、要) vêm sempre antes.",
    obs="想 + pessoa = sentir saudade: 我想你 (sinto sua falta)."),
   dict(title="Querer e pedir: 要", forma="S + 要 + N ／ S + 要 + V",
    funcao="Pedir algo (loja, restaurante) ou anunciar uma decisão",
    modo="Mais direto que 想; \"não quero (coisa)\" = 不要",
    ex=["我|—|要|一杯咖啡|—|Wǒ yào yì bēi kāfēi.|Quero um café.",
        "你|—|要|什么|—|Nǐ yào shénme?|O que você deseja?",
        "我|明天要|去|上海|—|Wǒ míngtiān yào qù Shànghǎi.|Amanhã vou a Xangai (já está decidido).",
        "我|不|要|糖|—|Wǒ bú yào táng.|Não quero açúcar."],
    wrong="我想一杯咖啡。", right="我要一杯咖啡。",
    erro="Usar 想 com substantivo para pedir. 想 + substantivo = sentir falta; para pedir, use 要 + coisa.",
    obs="不要 + verbo é uma ordem negativa: 不要走！ = Não vá! (Lição 17)."),
   dict(title="Propósito: 去 / 来 + lugar + V", forma="S + 去/来 + lugar + V + O",
    funcao="Dizer para que se vai a um lugar",
    modo="Afirmativo; os dois verbos ficam em série, sem conector, na ordem real das ações",
    ex=["我|—|去超市|买东西|—|Wǒ qù chāoshì mǎi dōngxi.|Vou ao supermercado fazer compras.",
        "马克|—|来中国|学习中文|—|Mǎkè lái Zhōngguó xuéxí Zhōngwén.|O Mark veio à China estudar chinês.",
        "我们|明天|去公园|跑步|—|Wǒmen míngtiān qù gōngyuán pǎobù.|Amanhã vamos ao parque correr.",
        "她|—|去银行|取钱|了|Tā qù yínháng qǔ qián le.|Ela foi ao banco sacar dinheiro."],
    wrong="我去超市为了买东西。", right="我去超市买东西。",
    erro="Traduzir \"para\" com 为了 em frases simples. No propósito de deslocamento, o segundo verbo vem logo depois do lugar.",
    obs="Primeiro vai, depois faz: a ordem dos verbos segue a ordem dos acontecimentos."),
  ]),
 dict(n=14, t="请等一下！", py="Qǐng děng yíxià!", pt="Espere um pouquinho, por favor!",
  obj=["Fazer pedidos educados com 请 + verbo",
       "Suavizar ações com verbo + 一下 e com verbo duplicado",
       "Descrever ações em andamento com 在 / 正在 … (呢)"],
  pts=[
   dict(title="Pedido: 请 + V", forma="请 + V + O",
    funcao="Pedir ou convidar com educação",
    modo="Imperativo educado; 请 abre o pedido",
    ex=["—|请|坐|—|—|Qǐng zuò.|Sente-se, por favor.",
        "—|请|喝|茶|—|Qǐng hē chá.|Tome um chá, por favor.",
        "—|请再|说|一遍|—|Qǐng zài shuō yí biàn.|Repita, por favor.",
        "—|请|进|—|—|Qǐng jìn.|Entre, por favor."],
    wrong="坐请。", right="请坐。",
    erro="Colocar 请 no fim, como em \"sente-se, por favor\". 请 vem antes do verbo.",
    obs="请 também é convidar e pagar: 我请你吃饭 = te convido para comer (eu pago)."),
   dict(title="Suavizar: V + 一下 ／ VV", forma="V + 一下 + O ／ VV (看看、试试)",
    funcao="Indicar ação rápida ou deixar o pedido mais leve",
    modo="Afirmativo/imperativo; muito comum na fala",
    ex=["—|请|等|一下|—|Qǐng děng yíxià.|Espere um pouquinho.",
        "你|—|看看|这本书|—|Nǐ kànkan zhè běn shū.|Dê uma olhada neste livro.",
        "我|可以|试|一下|吗|Wǒ kěyǐ shì yíxià ma?|Posso experimentar?",
        "我|—|问|一下|—|Wǒ wèn yíxià…|Deixa eu perguntar uma coisa…"],
    wrong="请一下等。", right="请等一下。",
    erro="Colocar 一下 antes do verbo. 一下 vem logo depois do verbo.",
    obs="Na duplicação, a segunda sílaba fica átona: 看看 (kànkan), 试试 (shìshi)."),
   dict(title="Em andamento: 在 / 正在 … (呢)", forma="S + (正)在 + V + O + (呢)",
    funcao="Dizer o que alguém está fazendo agora",
    modo="Afirmativo; 呢 no fim é opcional e reforça",
    ex=["我|在|吃|饭|呢|Wǒ zài chī fàn ne.|Estou comendo.",
        "她|正在|看|电视|呢|Tā zhèngzài kàn diànshì ne.|Ela está vendo TV.",
        "马克|在|打|电话|—|Mǎkè zài dǎ diànhuà.|O Mark está ao telefone.",
        "你|在|做|什么|呢|Nǐ zài zuò shénme ne?|O que você está fazendo?"],
    wrong="我吃饭在。", right="我在吃饭。",
    erro="Colocar 在 depois do verbo, como o \"-ndo\" do português. 在 vem antes do verbo.",
    obs="Negativa: 没(在) + V: 我没在看电视 (não estou vendo TV)."),
  ]),
 dict(n=15, t="这里不能拍照。", py="Zhèlǐ bù néng pāizhào.", pt="Aqui não pode tirar foto.",
  obj=["Pedir e dar permissão com 可以",
       "Expressar proibição com 不能 / 不可以 e 别",
       "Descrever estados com verbo + 着"],
  pts=[
   dict(title="Permissão: 可以…吗？", forma="S + 可以 + V + O + 吗？",
    funcao="Pedir ou dar permissão",
    modo="Interrogativo/afirmativo; resposta: 可以 ／ 不可以 (ou 不行)",
    ex=["我|可以|进来|—|吗|Wǒ kěyǐ jìnlai ma?|Posso entrar?",
        "我|可以|坐|这儿|吗|Wǒ kěyǐ zuò zhèr ma?|Posso sentar aqui?",
        "你|可以|用|我的电脑|—|Nǐ kěyǐ yòng wǒ de diànnǎo.|Você pode usar meu computador.",
        "这儿|可以|拍|照|吗|Zhèr kěyǐ pāi zhào ma?|Pode tirar foto aqui?"],
    wrong="我会进来吗？", right="我可以进来吗？",
    erro="Usar 会 para pedir permissão. 会 = habilidade ou previsão; permissão é 可以.",
    obs="我可以…吗？ é a forma mais segura em lojas, aulas e casas de amigos."),
   dict(title="Proibição: 不能 / 不可以 / 别", forma="(lugar) + 不能/不可以 + V ／ 别 + V",
    funcao="Proibir ou avisar",
    modo="Negativo; 不能 / 不可以 para regras; 别 para pedidos diretos",
    ex=["这里|不能|拍|照|—|Zhèlǐ bù néng pāi zhào.|Aqui não pode tirar foto.",
        "这儿|不可以|抽|烟|—|Zhèr bù kěyǐ chōu yān.|Aqui não é permitido fumar.",
        "上课|不能|玩|手机|—|Shàngkè bù néng wán shǒujī.|Na aula não pode mexer no celular.",
        "你|别|说|话|—|Nǐ bié shuō huà.|Não fale."],
    wrong="这里没能拍照。", right="这里不能拍照。",
    erro="Usar 没 para proibir. Regras e proibições usam 不能 ou 不可以; 没 é para fatos que não aconteceram.",
    obs="Placas usam 禁止 (jìnzhǐ): 禁止吸烟 = proibido fumar."),
   dict(title="Estado: V + 着", forma="S + V + 着 (+ O)",
    funcao="Descrever um estado que continua (porta aberta, luz acesa, sentado)",
    modo="Afirmativo; descreve o resultado ou a postura, não a ação em progresso",
    ex=["门|—|开着|—|—|Mén kāizhe.|A porta está aberta.",
        "灯|—|开着|—|呢|Dēng kāizhe ne.|A luz está acesa.",
        "她|—|穿着|红衣服|—|Tā chuānzhe hóng yīfu.|Ela está de roupa vermelha.",
        "他|—|坐着|—|—|Tā zuòzhe.|Ele está sentado."],
    wrong="门在开。", right="门开着。",
    erro="Usar 在 para estados. 在 + verbo indica a ação acontecendo (abrindo agora); o estado resultante é verbo + 着.",
    obs="他在穿衣服 (está se vestindo) × 他穿着衣服 (está vestido)."),
  ]),
 dict(n=16, t="我一边吃饭一边看电视。", py="Wǒ yìbiān chī fàn yìbiān kàn diànshì.", pt="Eu vejo TV enquanto como.",
  obj=["Encadear ações com 先…然后 / 再…",
       "Marcar \"depois de\" com …以后",
       "Fazer duas ações ao mesmo tempo com 一边…一边…"],
  pts=[
   dict(title="Sequência: 先…然后 / 再…", forma="S + 先 + V1，然后 / 再 + V2",
    funcao="Dizer a ordem das ações",
    modo="Afirmativo; 然后 para relatos, 再 para planos e pedidos",
    ex=["我|先|洗|手|—|Wǒ xiān xǐ shǒu,|Primeiro lavo as mãos,",
        "—|然后|吃|饭|—|ránhòu chī fàn.|depois como.",
        "你|先|做|作业|—|Nǐ xiān zuò zuòyè,|Primeiro faça o dever,",
        "—|再|看|电视|—|zài kàn diànshì.|depois veja TV."],
    wrong="我吃饭先洗手。", right="我先洗手，然后吃饭。",
    erro="Colocar 先 depois do verbo ou seguir a ordem do português. 先 vem antes da primeira ação, e as frases seguem a ordem real.",
    obs="Em pedidos e planos, prefira 再: 先吃饭再走 (primeiro coma, depois vá)."),
   dict(title="Depois de: …以后", forma="V1 + O + 以后，S + V2",
    funcao="Indicar que uma ação acontece depois da outra",
    modo="以后 fecha a primeira oração (ordem inversa ao português \"depois de…\")",
    ex=["我|下课以后|去|图书馆|—|Wǒ xiàkè yǐhòu qù túshūguǎn.|Depois da aula vou à biblioteca.",
        "她|吃饭以后|散|步|—|Tā chī fàn yǐhòu sàn bù.|Depois de comer ela passeia.",
        "马克|到北京以后|找|工作|了|Mǎkè dào Běijīng yǐhòu zhǎo gōngzuò le.|Depois de chegar a Pequim, o Mark procurou emprego.",
        "我|回家以后|做|饭|—|Wǒ huí jiā yǐhòu zuò fàn.|Depois de chegar em casa, cozinho."],
    wrong="我以后下课去图书馆。", right="我下课以后去图书馆。",
    erro="Colocar 以后 antes da ação, como \"depois de\". Em chinês, 以后 vem depois: 下课以后.",
    obs="以后 sozinho = \"no futuro\": 以后我想去中国."),
   dict(title="Ao mesmo tempo: 一边…一边…", forma="S + 一边 + V1，一边 + V2",
    funcao="Fazer duas ações simultâneas",
    modo="Afirmativo; o sujeito é o mesmo nas duas ações",
    ex=["我|一边吃饭，一边|看|电视|—|Wǒ yìbiān chī fàn, yìbiān kàn diànshì.|Vejo TV enquanto como.",
        "她|一边听音乐，一边|做|作业|—|Tā yìbiān tīng yīnyuè, yìbiān zuò zuòyè.|Ela faz o dever ouvindo música.",
        "我们|一边走，一边|聊|天|—|Wǒmen yìbiān zǒu, yìbiān liáo tiān.|Conversamos enquanto caminhamos.",
        "马克|一边喝咖啡，一边|看|报纸|—|Mǎkè yìbiān hē kāfēi, yìbiān kàn bàozhǐ.|O Mark lê o jornal tomando café."],
    wrong="我吃饭一边看电视。", right="我一边吃饭，一边看电视。",
    erro="Usar 一边 só uma vez. A estrutura pede 一边 antes de cada um dos dois verbos.",
    obs="Com verbos curtos, pode-se usar 边…边…: 边吃边聊 (conversar comendo)."),
  ]),
 dict(n=17, t="别太累了！", py="Bié tài lèi le!", pt="Não se canse demais!",
  obj=["Pedir que alguém não faça algo com 别 / 不要",
       "Expressar obrigação com 得 (děi) e 应该",
       "Dizer que algo não é necessário com 不用"],
  pts=[
   dict(title="Pedido negativo: 别 / 不要", forma="(你) + 别/不要 + V (+ 了)",
    funcao="Pedir que alguém não faça algo",
    modo="Imperativo negativo; 别 é mais curto e coloquial",
    ex=["你|别|担心|—|—|Nǐ bié dānxīn.|Não se preocupe.",
        "—|不要|迟到|—|—|Bú yào chídào.|Não se atrase.",
        "你|别太|累|—|了|Nǐ bié tài lèi le!|Não se canse demais!",
        "你|别|忘了|带护照|—|Nǐ bié wàngle dài hùzhào.|Não esqueça de levar o passaporte."],
    wrong="你不担心。", right="你别担心。",
    erro="Usar 不 para pedir que alguém não faça algo. 不 descreve (\"você não se preocupa\"); para pedir, use 别 ou 不要.",
    obs="别…了 pede que alguém pare: 别说了！ = Pare de falar!"),
   dict(title="Obrigação: 得 (děi) / 应该", forma="S + 得/应该 + V + O",
    funcao="Dizer o que é preciso ou o que se deve fazer",
    modo="得 = ter que (fala); 应该 = deveria (conselho, norma)",
    ex=["我|得|走|—|了|Wǒ děi zǒu le.|Tenho que ir.",
        "你|应该多|休息|—|—|Nǐ yīnggāi duō xiūxi.|Você deveria descansar mais.",
        "我们|明天得|上|班|—|Wǒmen míngtiān děi shàng bān.|Amanhã temos que trabalhar.",
        "学生|应该|做|作业|—|Xuésheng yīnggāi zuò zuòyè.|Os alunos devem fazer o dever."],
    wrong="我不得走。", right="我不用走。",
    erro="Negar 得 (děi) com 不. A negativa de \"ter que\" é 不用 (não precisa) — ponto C.",
    obs="得 tem três leituras: děi (ter que), de (Lição 20: 说得好) e dé (obter). O contexto decide."),
   dict(title="Não precisa: 不用", forma="S + 不用 + V",
    funcao="Dizer que algo não é necessário",
    modo="Negativo; também é resposta educada a agradecimentos (不用谢)",
    ex=["你|不用|来|—|—|Nǐ bú yòng lái.|Você não precisa vir.",
        "明天|不用|上|班|—|Míngtiān bú yòng shàng bān.|Amanhã não precisa trabalhar.",
        "你|不用|买|票|—|Nǐ bú yòng mǎi piào.|Você não precisa comprar passagem.",
        "—|不用|谢|—|—|Bú yòng xiè.|De nada (não precisa agradecer)."],
    wrong="你别来。（＝ não precisa vir）", right="你不用来。",
    erro="Confundir 别 (não faça!) com 不用 (não precisa). 你别来 proíbe; 你不用来 só libera.",
    obs="不用 libera; 别 proíbe — a troca muda totalmente o tom da frase."),
  ]),
 dict(n=18, t="我的爱好是运动。", py="Wǒ de àihào shì yùndòng.", pt="Meu hobby é praticar esportes.",
  obj=["Falar de capacidade e possibilidade com 能",
       "Falar de hobbies com 爱好是 + verbo",
       "Dizer \"antes de\" com …以前"],
  pts=[
   dict(title="Poder / conseguir: 能", forma="S + 能 + V + O",
    funcao="Dizer se é possível fazer algo (tempo, saúde, situação, capacidade física)",
    modo="Afirmativo/negativo (不能); vem antes do verbo principal",
    ex=["你|明天能|来|—|吗|Nǐ míngtiān néng lái ma?|Você pode vir amanhã?",
        "我|今天不能|喝|酒|—|Wǒ jīntiān bù néng hē jiǔ.|Hoje não posso beber.",
        "他|能|跑|十公里|—|Tā néng pǎo shí gōnglǐ.|Ele consegue correr 10 km.",
        "这儿|能|上|网|吗|Zhèr néng shàng wǎng ma?|Dá para acessar a internet aqui?"],
    wrong="我不会去，我很忙。", right="我不能去，我很忙。",
    erro="Usar 会 para impossibilidade por circunstância. 会 = saber fazer; 能 = poder (tempo, saúde, situação).",
    obs="会 (aprendeu) × 能 (consegue / pode) × 可以 (tem permissão)."),
   dict(title="Hobbies: 爱好是 + V", forma="S 的 爱好 是 + V + O",
    funcao="Falar de hobbies e interesses",
    modo="Afirmativo; o verbo funciona como substantivo sem mudar de forma",
    ex=["我的爱好|—|是|运动|—|Wǒ de àihào shì yùndòng.|Meu hobby é praticar esportes.",
        "马克的爱好|—|是|看电影|—|Mǎkè de àihào shì kàn diànyǐng.|O hobby do Mark é ver filmes.",
        "她的爱好|—|是|唱歌|—|Tā de àihào shì chàng gē.|O hobby dela é cantar.",
        "你的爱好|—|是|什么|—|Nǐ de àihào shì shénme?|Qual é o seu hobby?"],
    wrong="我的爱好是看电影的事。", right="我的爱好是看电影。",
    erro="Acrescentar uma palavra para \"transformar\" o verbo em substantivo. Em chinês, o verbo entra direto depois de 是.",
    obs="Outra forma comum: 我喜欢 + verbo (我喜欢看电影)."),
   dict(title="Antes de: …以前", forma="V1 + O + 以前，S + V2",
    funcao="Dizer o que acontece antes de outra ação",
    modo="以前 fecha a primeira oração; o verbo não muda",
    ex=["我|睡觉以前|看|书|—|Wǒ shuìjiào yǐqián kàn shū.|Antes de dormir, leio.",
        "我们|吃饭以前|洗|手|—|Wǒmen chī fàn yǐqián xǐ shǒu.|Antes de comer, lavamos as mãos.",
        "你|出门以前|关|灯|—|Nǐ chūmén yǐqián guān dēng.|Antes de sair, apague a luz.",
        "马克|上课以前|喝|咖啡|—|Mǎkè shàngkè yǐqián hē kāfēi.|O Mark toma café antes da aula."],
    wrong="我以前睡觉看书。", right="我睡觉以前看书。",
    erro="Colocar 以前 antes da ação. Como 以后, 以前 vem depois: 睡觉以前 = antes de dormir.",
    obs="以前 sozinho = \"antigamente\": 以前我住在巴西."),
  ]),
 dict(n=19, t="我吃过北京烤鸭。", py="Wǒ chīguo Běijīng kǎoyā.", pt="Já comi pato laqueado de Pequim.",
  obj=["Falar de experiências com verbo + 过",
       "Indicar mudança de situação com 了 no fim da frase",
       "Expressar mudança gradual com 越来越"],
  pts=[
   dict(title="Experiência: V + 过", forma="S + V + 过 + O",
    funcao="Dizer que já se fez algo alguma vez",
    modo="Afirmativo/negativo (没 + V + 过); pergunta: V过…吗？",
    ex=["我|—|吃过|北京烤鸭|—|Wǒ chīguo Běijīng kǎoyā.|Já comi pato laqueado de Pequim.",
        "你|—|去过|中国|吗|Nǐ qùguo Zhōngguó ma?|Você já foi à China?",
        "马克|没|看过|这个电影|—|Mǎkè méi kànguo zhège diànyǐng.|O Mark nunca viu este filme.",
        "我|—|学过|一点儿日语|—|Wǒ xuéguo yìdiǎnr Rìyǔ.|Já estudei um pouco de japonês."],
    wrong="我没吃过了北京烤鸭。", right="我没吃过北京烤鸭。",
    erro="Somar 了 à negativa com 过. Na negativa, fica só 没 + verbo + 过.",
    obs="了 = fez (fato concluído); 过 = já teve a experiência."),
   dict(title="Mudança: … 了 no fim", forma="S + adj / V + 了",
    funcao="Dizer que a situação mudou (\"ficou\", \"agora…\")",
    modo="Afirmativo; o 了 no fim da frase marca a mudança",
    ex=["天|—|冷|—|了|Tiān lěng le.|Esfriou.",
        "我|—|饿|—|了|Wǒ è le.|Fiquei com fome.",
        "她|—|是|大学生|了|Tā shì dàxuéshēng le.|Agora ela é universitária.",
        "外面|—|下|雨|了|Wàimiàn xià yǔ le.|Começou a chover lá fora."],
    wrong="天变冷。", right="天冷了。",
    erro="Traduzir \"ficou\" com um verbo a mais. Em chinês, a mudança se marca com 了 no fim.",
    obs="不…了 = não mais: 我不喝咖啡了 (parei de tomar café)."),
   dict(title="Cada vez mais: 越来越", forma="S + 越来越 + adj / V",
    funcao="Expressar uma mudança gradual",
    modo="Afirmativo; não se usa 很 junto; costuma terminar com 了",
    ex=["天气|越来越|热|—|了|Tiānqì yuè lái yuè rè le.|O tempo está cada vez mais quente.",
        "你的中文|越来越|好|—|了|Nǐ de Zhōngwén yuè lái yuè hǎo le.|Seu chinês está cada vez melhor.",
        "东西|越来越|贵|—|—|Dōngxi yuè lái yuè guì.|As coisas estão cada vez mais caras.",
        "我|越来越|喜欢|北京|了|Wǒ yuè lái yuè xǐhuan Běijīng le.|Gosto cada vez mais de Pequim."],
    wrong="天气越来越很热。", right="天气越来越热了。",
    erro="Usar 很 com 越来越. A expressão já indica grau; 很 sobra.",
    obs="Termina muitas vezes com 了 porque também expressa mudança (ponto B)."),
  ]),
 dict(n=20, t="你怎么了？", py="Nǐ zěnme le?", pt="O que houve com você?",
  obj=["Perguntar o que houve com 怎么了 e responder",
       "Destacar quando, como ou onde algo aconteceu com 是…的",
       "Avaliar ações com verbo + 得 + adjetivo"],
  pts=[
   dict(title="O que houve: 怎么了？", forma="S + 怎么了？ → S + V/adj + 了",
    funcao="Perguntar o que aconteceu e explicar",
    modo="Interrogativo/afirmativo; a resposta costuma levar 了",
    ex=["你|—|怎么|—|了|Nǐ zěnme le?|O que houve com você?",
        "我|—|感冒|—|了|Wǒ gǎnmào le.|Peguei um resfriado.",
        "我|—|头疼|—|—|Wǒ tóu téng.|Estou com dor de cabeça.",
        "她|—|发烧|—|了|Tā fāshāo le.|Ela está com febre."],
    wrong="你怎么？", right="你怎么了？",
    erro="Esquecer 了 em 怎么了. Sem 了, 怎么 pergunta \"como\" e a frase fica incompleta.",
    obs="怎么 + verbo = como fazer: 怎么去？ (como se vai?)."),
   dict(title="Ênfase: 是…的", forma="S + 是 + (quando/como/onde) + V + 的",
    funcao="Destacar uma circunstância de algo que já aconteceu",
    modo="Afirmativo (fato passado e conhecido); 是 pode cair, 的 não",
    ex=["我|是坐飞机|来|—|的|Wǒ shì zuò fēijī lái de.|Eu vim de avião.",
        "她|是昨天|到|—|的|Tā shì zuótiān dào de.|Foi ontem que ela chegou.",
        "你|是在哪儿|学|中文|的|Nǐ shì zài nǎr xué Zhōngwén de?|Onde foi que você aprendeu chinês?",
        "马克|是跟朋友一起|去|—|的|Mǎkè shì gēn péngyou yìqǐ qù de.|O Mark foi com amigos."],
    wrong="我是坐飞机来了。", right="我是坐飞机来的。",
    erro="Usar 了 no lugar de 的. Quando a ação já é conhecida e se destaca o como / quando / onde, a frase fecha com 的.",
    obs="Use 是…的 quando o fato já é sabido: \"Você veio. Como?\" → 我是坐飞机来的."),
   dict(title="Avaliar ações: V + 得 + adj", forma="S + (O) + V + 得 + (很) adj",
    funcao="Dizer como alguém faz algo (bem, rápido, tarde)",
    modo="Afirmativo/negativo (V得不好); com objeto, ele vem antes do verbo ou o verbo se repete",
    ex=["你|—|说得|很好|—|Nǐ shuō de hěn hǎo.|Você fala muito bem.",
        "她|唱歌|唱得|很好听|—|Tā chàng gē chàng de hěn hǎotīng.|Ela canta muito bem.",
        "马克|中文|说得|很流利|—|Mǎkè Zhōngwén shuō de hěn liúlì.|O Mark fala chinês fluentemente.",
        "我|今天|起得|很晚|—|Wǒ jīntiān qǐ de hěn wǎn.|Hoje acordei tarde."],
    wrong="他说中文得很好。", right="他中文说得很好。",
    erro="Colocar o objeto entre o verbo e 得. Depois do verbo vem direto 得; o objeto vai antes (ou repete-se o verbo: 他说中文说得很好).",
    obs="Aqui 得 se lê de (átono) e liga o verbo à avaliação."),
  ]),
 dict(n=21, t="我觉得你说得对。", py="Wǒ juéde nǐ shuō de duì.", pt="Acho que você tem razão.",
  obj=["Dar opiniões com 觉得 / 认为",
       "Relatar falas com 说 e 听说",
       "Sugerir e supor com a partícula 吧"],
  pts=[
   dict(title="Opinião: 觉得 / 认为", forma="S + 觉得/认为 + oração",
    funcao="Dar uma opinião",
    modo="Afirmativo/negativo; a oração depois de 觉得 segue as regras normais",
    ex=["我|—|觉得|你说得对|—|Wǒ juéde nǐ shuō de duì.|Acho que você tem razão.",
        "我|—|觉得|中文不太难|—|Wǒ juéde Zhōngwén bú tài nán.|Acho que o chinês não é muito difícil.",
        "你|—|觉得|这个怎么样|—|Nǐ juéde zhège zěnmeyàng?|O que você acha disto?",
        "老师|—|认为|我们应该多练习|—|Lǎoshī rènwéi wǒmen yīnggāi duō liànxí.|O professor acha que devemos praticar mais."],
    wrong="我觉得中文是不太难。", right="我觉得中文不太难。",
    erro="Colocar 是 antes do adjetivo dentro da opinião. A oração depois de 觉得 segue as regras normais: adjetivo sem 是 (Lição 4).",
    obs="觉得 é mais pessoal e falado; 认为 é mais formal e argumentativo."),
   dict(title="Citação: 说 / 听说", forma="S + 说 + fala ／ 听说 + informação",
    funcao="Relatar o que alguém disse ou algo que se ouviu",
    modo="Afirmativo; não existe \"que\" conectivo e o verbo citado não muda",
    ex=["马克|—|说|他明天不来|—|Mǎkè shuō tā míngtiān bù lái.|O Mark disse que amanhã não vem.",
        "老师|—|说|明天有考试|—|Lǎoshī shuō míngtiān yǒu kǎoshì.|O professor disse que amanhã tem prova.",
        "我|—|听说|她结婚了|—|Wǒ tīngshuō tā jiéhūn le.|Ouvi dizer que ela se casou.",
        "—|—|听说|这个饭馆很好吃|—|Tīngshuō zhège fànguǎn hěn hǎochī.|Dizem que este restaurante é ótimo."],
    wrong="马克说那他明天不来。", right="马克说他明天不来。",
    erro="Acrescentar uma palavra para \"que\" depois de 说. Em chinês, a fala relatada vem direto.",
    obs="听说 abre a frase quando a fonte não importa: 听说… = dizem que…."),
   dict(title="Sugestão e suposição: 吧", forma="Frase + 吧",
    funcao="Sugerir (\"vamos…\"), supor (\"…, né?\") ou suavizar uma ordem",
    modo="Partícula final; sem 吧, a frase soa mais seca",
    ex=["我们|—|走|—|吧|Wǒmen zǒu ba.|Vamos embora.",
        "你|—|是|马克|吧|Nǐ shì Mǎkè ba?|Você é o Mark, né?",
        "我们|明天|去|长城|吧|Wǒmen míngtiān qù Chángchéng ba.|Vamos à Grande Muralha amanhã.",
        "他|应该|到|—|了吧|Tā yīnggāi dào le ba.|Ele já deve ter chegado."],
    wrong="你是马克吗吧？", right="你是马克吧？",
    erro="Juntar 吗 e 吧. Use 吗 para perguntar sem saber; use 吧 quando já supõe a resposta.",
    obs="吧 suaviza ordens: 坐吧 (senta aí), 吃吧 (pode comer)."),
  ]),
 dict(n=22, t="这是我买的书。", py="Zhè shì wǒ mǎi de shū.", pt="Este é o livro que eu comprei.",
  obj=["Modificar substantivos com orações (verbo + 的 + N)",
       "Formar orações relativas negativas com 不 / 没",
       "Diferenciar 的, 地 e 得"],
  pts=[
   dict(title="Oração relativa: … V + 的 + N", forma="(S) + V + (O) + 的 + N",
    funcao="Descrever um substantivo com uma ação (\"o livro que comprei\")",
    modo="A oração inteira vem ANTES do substantivo, ligada por 的",
    ex=["这|—|是|我买的书|—|Zhè shì wǒ mǎi de shū.|Este é o livro que eu comprei.",
        "妈妈做的菜|很|好吃|—|—|Māma zuò de cài hěn hǎochī.|A comida que a mamãe faz é gostosa.",
        "昨天来的人|—|是|我朋友|—|Zuótiān lái de rén shì wǒ péngyou.|A pessoa que veio ontem é minha amiga.",
        "你|—|看|我拍的照片|吧|Nǐ kàn wǒ pāi de zhàopiàn ba.|Veja as fotos que eu tirei."],
    wrong="这是书我买的。", right="这是我买的书。",
    erro="Colocar a oração depois do substantivo, como em \"o livro que comprei\". Em chinês, ela vem antes: 我买的书.",
    obs="Não existe \"que\" relativo: 的 faz esse papel."),
   dict(title="Relativa negativa: 不 / 没 + V + 的 + N", forma="不/没 + V + 的 + N",
    funcao="Descrever algo pelo que não se faz ou não aconteceu",
    modo="不 = hábito ou vontade; 没 = não aconteceu",
    ex=["这儿|—|有|很多我不认识的字|—|Zhèr yǒu hěn duō wǒ bú rènshi de zì.|Aqui há muitos caracteres que eu não conheço.",
        "这|—|是|我没看过的电影|—|Zhè shì wǒ méi kànguo de diànyǐng.|Este é um filme que eu nunca vi.",
        "不吃肉的人|很|多|—|—|Bù chī ròu de rén hěn duō.|Há muita gente que não come carne.",
        "没来的同学|明天|考|试|—|Méi lái de tóngxué míngtiān kǎo shì.|Os colegas que não vieram fazem a prova amanhã."],
    wrong="这是我没看过电影的。", right="这是我没看过的电影。",
    erro="Deslocar 的 para o fim. 的 fica entre a oração e o substantivo: 没看过的电影.",
    obs="Não use 是 dentro da oração relativa: 我买的书, nunca 我是买的书."),
   dict(title="的, 地 e 得", forma="adj + 的 + N ／ adj + 地 + V ／ V + 得 + adj",
    funcao="Ligar modificadores a substantivos, verbos e avaliações",
    modo="Os três se leem de; a escrita muda conforme a função",
    ex=["她|—|是|很认真的学生|—|Tā shì hěn rènzhēn de xuésheng.|Ela é uma aluna muito dedicada.",
        "她|很认真地|学习|—|—|Tā hěn rènzhēn de xuéxí.|Ela estuda com dedicação.",
        "她|—|学得|很认真|—|Tā xué de hěn rènzhēn.|Ela estuda de forma dedicada.",
        "孩子们|高兴地|唱|歌|—|Háizimen gāoxìng de chàng gē.|As crianças cantam alegremente."],
    wrong="她很认真的学习。", right="她很认真地学习。",
    erro="Usar 的 antes de verbo. Antes de substantivo vai 的; antes de verbo vai 地; depois do verbo, para avaliar, vai 得.",
    obs="Na escrita informal, até nativos confundem; em textos e provas a distinção é cobrada."),
  ]),
 dict(n=23, t="借书的时候要带学生证。", py="Jiè shū de shíhou yào dài xuéshēngzhèng.", pt="Para pegar livros emprestados, é preciso levar a carteirinha.",
  obj=["Indicar o momento de uma ação com …的时候",
       "Expressar \"assim que\" com 一…就…",
       "Indicar o resultado da ação com complementos (完、懂、到)"],
  pts=[
   dict(title="Quando: …的时候", forma="V / adj / N + 的时候，S + V",
    funcao="Dizer em que momento algo acontece",
    modo="A oração com 的时候 vem primeiro",
    ex=["—|借书的时候|要带|学生证|—|Jiè shū de shíhou yào dài xuéshēngzhèng.|Para pegar livros emprestados, é preciso levar a carteirinha.",
        "我|小时候|住在|巴西|—|Wǒ xiǎo shíhou zhù zài Bāxī.|Quando era criança, morei no Brasil.",
        "我|吃饭的时候不|看|手机|—|Wǒ chī fàn de shíhou bú kàn shǒujī.|Não olho o celular quando estou comendo.",
        "你|有空的时候给我|打|电话|吧|Nǐ yǒu kòng de shíhou gěi wǒ dǎ diànhuà ba.|Quando estiver livre, me ligue."],
    wrong="的时候我借书，要带学生证。", right="借书的时候要带学生证。",
    erro="Colocar 的时候 no início, como \"quando…\". Em chinês, 的时候 fecha a oração: 借书的时候.",
    obs="什么时候 pergunta \"quando\": 你什么时候来？"),
   dict(title="Assim que: 一…就…", forma="S + 一 + V1，(S) + 就 + V2",
    funcao="Dizer que uma ação vem logo depois da outra",
    modo="Afirmativo; 一 e 就 ficam antes dos verbos",
    ex=["我|一到家就|睡|觉|了|Wǒ yí dào jiā jiù shuì jiào le.|Assim que cheguei em casa, fui dormir.",
        "她|一下课就|回|家|—|Tā yí xiàkè jiù huí jiā.|Assim que a aula acaba, ela vai para casa.",
        "我|一喝咖啡就|睡不着|—|—|Wǒ yì hē kāfēi jiù shuì bu zháo.|É só eu tomar café que não consigo dormir.",
        "马克|一看就|懂|—|了|Mǎkè yí kàn jiù dǒng le.|O Mark entendeu na hora."],
    wrong="我到家一就睡觉了。", right="我一到家就睡觉了。",
    erro="Colocar 一 depois do verbo. 一 e 就 vêm antes de cada verbo: 一到家，就睡觉.",
    obs="O tom de 一 muda: yī sozinho; yí antes de 4º tom (一到); yì antes dos outros (一喝)."),
   dict(title="Resultado: V + 完 / 懂 / 到", forma="S + V + 完/懂/到 + (O) + (了)",
    funcao="Dizer se a ação chegou ao resultado",
    modo="Afirmativo/negativo (没 + V + resultado)",
    ex=["我|—|看完|这本书|了|Wǒ kànwán zhè běn shū le.|Terminei de ler este livro.",
        "你|—|听懂|—|了吗|Nǐ tīngdǒng le ma?|Você entendeu?",
        "我|—|找到|我的钥匙|了|Wǒ zhǎodào wǒ de yàoshi le.|Encontrei minhas chaves.",
        "我|还没|做完|作业|—|Wǒ hái méi zuòwán zuòyè.|Ainda não terminei o dever."],
    wrong="我看了，但是没看懂了。", right="我看了，但是没看懂。",
    erro="Manter 了 na negativa do resultado. Com 没, o 了 sai: 没看懂.",
    obs="看 (olhar) × 看懂 (entender lendo) × 看完 (terminar de ler): o complemento muda o sentido."),
  ]),
 dict(n=24, t="请把门关上。", py="Qǐng bǎ mén guānshang.", pt="Feche a porta, por favor.",
  obj=["Indicar para quem se faz a ação com 给 + pessoa + verbo",
       "Usar a estrutura 把 para dizer o que se faz com um objeto",
       "Formar a voz passiva com 被"],
  pts=[
   dict(title="Para alguém: 给 + pessoa + V", forma="S + 给 + pessoa + V + O",
    funcao="Indicar para quem se faz a ação",
    modo="Afirmativo; 给 + pessoa formam um bloco antes do verbo",
    ex=["我|给你|打|电话|—|Wǒ gěi nǐ dǎ diànhuà.|Eu te ligo.",
        "妈妈|给我|做|饭|—|Māma gěi wǒ zuò fàn.|A mamãe cozinha para mim.",
        "马克|给女朋友|买了|花|—|Mǎkè gěi nǚpéngyou mǎile huā.|O Mark comprou flores para a namorada.",
        "你|给我|看|一下|吧|Nǐ gěi wǒ kàn yíxià ba.|Deixa eu ver."],
    wrong="我给打电话你。", right="我给你打电话。",
    erro="Separar 给 da pessoa. 给 + pessoa formam um bloco que vem antes do verbo.",
    obs="No Sul também se ouve 打电话给你; a forma padrão é 给你打电话."),
   dict(title="Estrutura 把", forma="S + 把 + O + V + complemento",
    funcao="Dizer o que se faz com um objeto específico (mover, fechar, terminar, entregar)",
    modo="Afirmativo/imperativo; o verbo nunca fica sozinho: precisa de complemento (上、完、在…、给…)",
    ex=["—|请把门|关|上|—|Qǐng bǎ mén guānshang.|Feche a porta, por favor.",
        "我|把作业|做|完|了|Wǒ bǎ zuòyè zuòwán le.|Terminei o dever.",
        "你|把书|放在|桌子上|—|Nǐ bǎ shū fàng zài zhuōzi shang.|Coloque o livro em cima da mesa.",
        "她|把钱|给|我|了|Tā bǎ qián gěi wǒ le.|Ela me deu o dinheiro."],
    wrong="请把门关。", right="请把门关上。",
    erro="Deixar o verbo sozinho no fim. Com 把, o verbo precisa de complemento: 关上、做完、放在….",
    obs="Na tabela, 把 + objeto aparece na coluna ADV porque fica antes do verbo."),
   dict(title="Passiva: 被", forma="Objeto + 被 + (agente) + V + complemento",
    funcao="Destacar quem sofreu a ação, geralmente algo desagradável",
    modo="Afirmativo; o verbo também precisa de complemento (了、完、走…)",
    ex=["我的手机|被小偷|偷|—|了|Wǒ de shǒujī bèi xiǎotōu tōu le.|Meu celular foi roubado.",
        "蛋糕|被弟弟|吃|完|了|Dàngāo bèi dìdi chīwán le.|O bolo foi todo comido pelo meu irmão.",
        "我的自行车|被|骑|走|了|Wǒ de zìxíngchē bèi qízǒu le.|Levaram a minha bicicleta.",
        "他|被老师|批评|—|了|Tā bèi lǎoshī pīpíng le.|Ele levou bronca do professor."],
    wrong="这本书被马克写了。", right="这本书是马克写的。",
    erro="Usar 被 para fatos neutros, como \"o livro foi escrito pelo Mark\". 被 sugere algo negativo; para fatos neutros, prefira 是…的 (Lição 20).",
    obs="被 aparece muito em notícias e reclamações: 被骗了 (fui enganado)."),
  ]),
 dict(n=25, t="要是便宜，我就买。", py="Yàoshi piányi, wǒ jiù mǎi.", pt="Se estiver barato, eu compro.",
  obj=["Formar condicionais com 如果 / 要是 …(的话)，就…",
       "Expressar concessão com 虽然…但是…",
       "Dizer \"mesmo que\" com 即使…也…"],
  pts=[
   dict(title="Condição: 如果 / 要是 … 就 …", forma="如果/要是 + condição (的话)，S + 就 + resultado",
    funcao="Dizer o que acontece se algo for verdade",
    modo="如果 = se (neutro); 要是 = se (falado); 的话 opcional; 就 vem depois do sujeito",
    ex=["我|要是有钱就|买|车|—|Wǒ yàoshi yǒu qián jiù mǎi chē.|Se eu tiver dinheiro, compro um carro.",
        "你|如果有问题就|问|我|吧|Nǐ rúguǒ yǒu wèntí jiù wèn wǒ ba.|Se tiver dúvidas, pergunte para mim.",
        "我们|明天要是下雨就不|去|公园|了|Wǒmen míngtiān yàoshi xià yǔ jiù bú qù gōngyuán le.|Se chover amanhã, não vamos mais ao parque.",
        "你|如果累了就|休息|一下|吧|Nǐ rúguǒ lèi le jiù xiūxi yíxià ba.|Se estiver cansado, descanse um pouco."],
    wrong="如果便宜，就我买。", right="如果便宜，我就买。",
    erro="Colocar 就 antes do sujeito. 就 é advérbio: fica depois do sujeito e antes do verbo.",
    obs="的话 deixa a frase mais falada: 要是便宜的话，我就买."),
   dict(title="Concessão: 虽然…但是…", forma="虽然 + fato，但是 + contraste",
    funcao="Reconhecer algo e apresentar um contraste (\"embora…\")",
    modo="Afirmativo; diferente do português, os dois conectores aparecem juntos",
    ex=["这件衣服|虽然很贵，但是很|好看|—|—|Zhè jiàn yīfu suīrán hěn guì, dànshì hěn hǎokàn.|Embora esta roupa seja cara, é muito bonita.",
        "中文|虽然很难，但是很|有意思|—|—|Zhōngwén suīrán hěn nán, dànshì hěn yǒu yìsi.|Embora difícil, o chinês é muito interessante.",
        "我|虽然很累，但是还得|工作|—|—|Wǒ suīrán hěn lèi, dànshì hái děi gōngzuò.|Embora cansado, ainda tenho que trabalhar.",
        "他|虽然是美国人，但是会|说|中文|—|Tā suīrán shì Měiguó rén, dànshì huì shuō Zhōngwén.|Embora seja americano, ele fala chinês."],
    wrong="虽然很贵，很好看。", right="虽然很贵，但是很好看。",
    erro="Usar 虽然 sem 但是 (ou 可是). Em chinês, o contraste é marcado nas duas partes da frase.",
    obs="但是 pode ser trocado por 可是 (mais falado)."),
   dict(title="Mesmo que: 即使…也…", forma="即使 + hipótese，S + 也 + resultado",
    funcao="Dizer que o resultado não muda, mesmo na hipótese",
    modo="Afirmativo/negativo; 也 vem depois do sujeito; na fala também 就是…也…",
    ex=["我|即使很忙也要|学|中文|—|Wǒ jíshǐ hěn máng yě yào xué Zhōngwén.|Mesmo ocupado, vou estudar chinês.",
        "我们|明天即使下雨也|去|—|—|Wǒmen míngtiān jíshǐ xià yǔ yě qù.|Mesmo que chova amanhã, nós vamos.",
        "你|即使不喜欢也要|吃|一点儿|—|Nǐ jíshǐ bù xǐhuan yě yào chī yìdiǎnr.|Mesmo que não goste, coma um pouco.",
        "我|即使有钱也不|买|这个|—|Wǒ jíshǐ yǒu qián yě bù mǎi zhège.|Mesmo que tivesse dinheiro, não compraria isto."],
    wrong="即使下雨，我们就去。", right="即使下雨，我们也去。",
    erro="Usar 就 com 即使. 即使 pede 也; 就 combina com 如果 / 要是 (ponto A).",
    obs="如果…就… (se… então) × 即使…也… (mesmo que… ainda assim)."),
  ]),
]
