# Mandarim Básico I — Manual de Aulas (Método Chunk) — Odu Creative
# Conteúdo das lições 1 a 12.
#
# Cada exemplo é uma linha "S|ADV|V|O|PART|pinyin|tradução".
# As colunas seguem a ORDEM REAL da frase em chinês: lendo da esquerda
# para a direita, lê-se a frase inteira.
#   S    = sujeito / tópico
#   ADV  = advérbio, tempo, lugar, negação, verbo auxiliar (会/想/能) e
#          locuções antes do verbo (在…, 用…, 比…, 把…)
#   V    = verbo / predicado (inclui adjetivo usado como predicado)
#   O    = objeto / complemento
#   PART = partícula final (了、吗、呢、吧)
# "—" = coluna vazia nesta frase.

LESSONS_A = [
 dict(n=1, t="我是马克。", py="Wǒ shì Mǎkè.", pt="Eu sou o Mark.",
  obj=["Apresentar-se e identificar pessoas e coisas com a estrutura A 是 B",
       "Fazer perguntas de sim/não com a partícula 吗",
       "Usar 也 para expressar \"também\""],
  pts=[
   dict(title="Identificação com 是", forma="A 是 B",
    funcao="Apresentar-se, identificar ou classificar pessoas e coisas (\"ser\")",
    modo="Afirmativo; 是 liga dois substantivos e não muda com a pessoa nem com o tempo",
    ex=["我|—|是|马克|—|Wǒ shì Mǎkè.|Eu sou o Mark.",
        "马克|—|是|美国人|—|Mǎkè shì Měiguó rén.|O Mark é americano.",
        "王老师|—|是|中国人|—|Wáng lǎoshī shì Zhōngguó rén.|A professora Wang é chinesa.",
        "我们|—|是|学生|—|Wǒmen shì xuésheng.|Nós somos estudantes."],
    wrong="我马克。", right="我是马克。",
    erro="Omitir 是 entre dois substantivos. Para dizer \"A é B\", o chinês precisa do verbo 是 entre eles.",
    obs="Negativa: 不是 (bú shì). 是 é igual para todas as pessoas: 我是、你是、他是."),
   dict(title="Perguntas com 吗", forma="A 是 B 吗？",
    funcao="Transformar uma afirmação em pergunta de sim/não",
    modo="Interrogativo; 吗 vai no fim e a ordem das palavras não muda",
    ex=["你|—|是|学生|吗|Nǐ shì xuésheng ma?|Você é estudante?",
        "马克|—|是|美国人|吗|Mǎkè shì Měiguó rén ma?|O Mark é americano?",
        "她|—|是|老师|吗|Tā shì lǎoshī ma?|Ela é professora?",
        "你|—|是|巴西人|吗|Nǐ shì Bāxī rén ma?|Você é brasileiro?"],
    wrong="是你学生吗？", right="你是学生吗？",
    erro="Inverter sujeito e verbo para perguntar. Em chinês, a ordem continua igual à da afirmação; só se acrescenta 吗 no fim.",
    obs="Respostas curtas: 是 (sim) / 不是 (não). 吗 não se junta a palavras interrogativas como 什么 e 谁."),
   dict(title="\"Também\" com 也", forma="A 也 是 B",
    funcao="Dizer que o predicado vale também para outro sujeito",
    modo="Afirmativo/negativo; 也 fica sempre entre o sujeito e o verbo",
    ex=["马克|—|是|学生|—|Mǎkè shì xuésheng.|O Mark é estudante.",
        "我|也|是|学生|—|Wǒ yě shì xuésheng.|Eu também sou estudante.",
        "安娜|也|是|美国人|—|Ānnà yě shì Měiguó rén.|A Ana também é americana.",
        "我们|也|是|巴西人|—|Wǒmen yě shì Bāxī rén.|Nós também somos brasileiros."],
    wrong="也我是学生。", right="我也是学生。",
    erro="Colocar 也 no início ou no fim da frase, como \"também\" em português. 也 é advérbio e vem antes do verbo.",
    obs="Negativa: 我也不是老师 (também não sou professor). 也 vem sempre antes de 不."),
  ]),
 dict(n=2, t="这是我的书。", py="Zhè shì wǒ de shū.", pt="Este é o meu livro.",
  obj=["Apontar e identificar objetos com 这 e 那",
       "Indicar posse com 的 (N1 的 N2)",
       "Perguntar \"o quê?\" e \"de quem?\" com 什么 e 谁的"],
  pts=[
   dict(title="Objetos com 这 / 那", forma="这 / 那 是 N",
    funcao="Apontar e identificar objetos (isto / aquilo é…)",
    modo="Afirmativo; 这 = perto de quem fala, 那 = longe; o chinês não tem artigo",
    ex=["这|—|是|书|—|Zhè shì shū.|Isto é um livro.",
        "那|—|是|词典|—|Nà shì cídiǎn.|Aquilo é um dicionário.",
        "这|—|是|杂志|—|Zhè shì zázhì.|Isto é uma revista.",
        "那|—|是|报纸|—|Nà shì bàozhǐ.|Aquilo é um jornal."],
    wrong="这书。", right="这是书。",
    erro="Omitir 是: 这 sozinho não forma frase. Para \"isto é…\", use 这是….",
    obs="Sem artigo: 书 pode ser \"um livro\", \"o livro\" ou \"livros\"; o contexto decide."),
   dict(title="Posse com 的", forma="N1 的 N2 （我的书、马克的词典）",
    funcao="Indicar a quem algo pertence (\"de\")",
    modo="的 liga o dono ao objeto; o dono vem primeiro (ordem inversa ao português)",
    ex=["这|—|是|我的书|—|Zhè shì wǒ de shū.|Este é o meu livro.",
        "那|—|是|马克的词典|—|Nà shì Mǎkè de cídiǎn.|Aquele é o dicionário do Mark.",
        "这|—|是|老师的伞|—|Zhè shì lǎoshī de sǎn.|Este é o guarda-chuva do professor.",
        "那|—|是|安娜的手机|—|Nà shì Ānnà de shǒujī.|Aquele é o celular da Ana."],
    wrong="这是书的我。", right="这是我的书。",
    erro="Copiar a ordem do português (\"livro de mim\"). Em chinês, o dono vem antes: 我的书.",
    obs="Com família e pessoas próximas, 的 costuma cair: 我妈妈 (minha mãe), 我朋友 (meu amigo)."),
   dict(title="Perguntas com 什么 e 谁的", forma="这是什么？ ／ 这是谁的 N？",
    funcao="Perguntar \"o que é?\" e \"de quem é?\"",
    modo="Interrogativo; a palavra interrogativa fica no lugar da resposta, sem 吗",
    ex=["这|—|是|什么|—|Zhè shì shénme?|O que é isto?",
        "那|—|是|谁的书|—|Nà shì shéi de shū?|De quem é aquele livro?",
        "这|—|是|什么书|—|Zhè shì shénme shū?|Que livro é este?",
        "这|—|是|谁的伞|—|Zhè shì shéi de sǎn?|De quem é este guarda-chuva?"],
    wrong="这是什么吗？", right="这是什么？",
    erro="Juntar 吗 a uma palavra interrogativa. 什么 e 谁 já fazem a pergunta; 吗 sobra.",
    obs="A resposta ocupa o lugar da pergunta: 这是什么？ → 这是书。"),
  ]),
 dict(n=3, t="这儿是商店。", py="Zhèr shì shāngdiàn.", pt="Aqui é uma loja.",
  obj=["Identificar lugares com 这儿 / 那儿 / 哪儿",
       "Perguntar onde fica algo com 在哪儿",
       "Perguntar preços com 多少钱"],
  pts=[
   dict(title="Lugares com 这儿 / 那儿", forma="这儿 / 那儿 是 lugar",
    funcao="Identificar lugares (aqui / ali é…)",
    modo="Afirmativo; 这儿 = aqui, 那儿 = ali; no Sul e em Taiwan: 这里 / 那里",
    ex=["这儿|—|是|商店|—|Zhèr shì shāngdiàn.|Aqui é uma loja.",
        "那儿|—|是|银行|—|Nàr shì yínháng.|Ali é o banco.",
        "这儿|—|是|我家|—|Zhèr shì wǒ jiā.|Aqui é a minha casa.",
        "那儿|—|是|医院|—|Nàr shì yīyuàn.|Ali é o hospital."],
    wrong="哪儿是商店。", right="这儿是商店。",
    erro="Usar 哪儿 em frase afirmativa. 哪儿 só aparece em perguntas; na afirmação, use 这儿 ou 那儿.",
    obs="这儿 e 这里 significam o mesmo; o 儿 final é típico do Norte (Pequim)."),
   dict(title="Onde fica: 在哪儿", forma="N 在 哪儿？",
    funcao="Perguntar onde fica uma pessoa, lugar ou coisa",
    modo="Interrogativo; 在 = estar / ficar; 哪儿 fica no lugar da resposta",
    ex=["银行|—|在|哪儿|—|Yínháng zài nǎr?|Onde fica o banco?",
        "洗手间|—|在|哪儿|—|Xǐshǒujiān zài nǎr?|Onde fica o banheiro?",
        "马克|—|在|哪儿|—|Mǎkè zài nǎr?|Onde está o Mark?",
        "银行|—|在|那儿|—|Yínháng zài nàr.|O banco fica ali."],
    wrong="银行是哪儿？", right="银行在哪儿？",
    erro="Usar 是 para localização. Para \"onde fica / onde está\", o verbo é 在.",
    obs="在 = estar / ficar (localização); 是 = ser (identidade)."),
   dict(title="Preço: 多少钱", forma="N 多少钱？",
    funcao="Perguntar o preço",
    modo="Interrogativo; normalmente sem verbo; resposta com 块 (falado) ou 元 (escrito)",
    ex=["这个|—|—|多少钱|—|Zhège duōshao qián?|Quanto custa isto?",
        "苹果|—|—|多少钱|—|Píngguǒ duōshao qián?|Quanto custam as maçãs?",
        "这本书|—|—|二十块|—|Zhè běn shū èrshí kuài.|Este livro custa 20 yuans.",
        "咖啡|—|—|十五块|—|Kāfēi shíwǔ kuài.|O café custa 15 yuans."],
    wrong="这个是多少钱吗？", right="这个多少钱？",
    erro="Acrescentar 吗 à pergunta de preço. 多少 já é interrogativo; 吗 sobra, e 是 costuma ficar de fora.",
    obs="块 (kuài) é o \"real\" do dia a dia; 元 (yuán) aparece nas etiquetas; 毛 (máo) = 10 centavos."),
  ]),
 dict(n=4, t="这个饭店很便宜。", py="Zhège fàndiàn hěn piányi.", pt="Este hotel é barato.",
  obj=["Descrever com adjetivos usando 很 + adjetivo, sem 是",
       "Negar adjetivos com 不",
       "Indicar grau com 非常 / 太…了 / 不太"],
  pts=[
   dict(title="Adjetivo como predicado: 很 + adj", forma="N 很 adj",
    funcao="Descrever pessoas, coisas e lugares",
    modo="Afirmativo; o adjetivo funciona como verbo; 很 é quase obrigatório e nem sempre significa \"muito\"",
    ex=["这个饭店|很|便宜|—|—|Zhège fàndiàn hěn piányi.|Este hotel é barato.",
        "北京|很|大|—|—|Běijīng hěn dà.|Pequim é grande.",
        "咖啡|很|贵|—|—|Kāfēi hěn guì.|O café é caro.",
        "她|很|漂亮|—|—|Tā hěn piàoliang.|Ela é bonita."],
    wrong="这个饭店是便宜。", right="这个饭店很便宜。",
    erro="Usar 是 antes de adjetivo, copiando o \"é\" do português. Com adjetivos, 是 sai e entra 很.",
    obs="Sem 很, a frase soa como comparação: 这个便宜，那个贵 (este é barato, aquele é caro)."),
   dict(title="Negativa: 不 + adj", forma="N 不 adj",
    funcao="Negar uma qualidade",
    modo="Negativo; 不 entra antes do adjetivo e 很 sai",
    ex=["这个饭店|不|贵|—|—|Zhège fàndiàn bú guì.|Este hotel não é caro.",
        "今天|不|冷|—|—|Jīntiān bù lěng.|Hoje não está frio.",
        "这本书|不|难|—|—|Zhè běn shū bù nán.|Este livro não é difícil.",
        "我|不|忙|—|—|Wǒ bù máng.|Não estou ocupado."],
    wrong="这个饭店不是贵。", right="这个饭店不贵。",
    erro="Negar adjetivo com 不是. 不是 nega substantivos (不是老师); adjetivos levam só 不.",
    obs="不 vira bú antes de 4º tom: 不贵 (bú guì), 不是 (bú shì)."),
   dict(title="Grau: 非常 / 太…了 / 不太", forma="非常 adj ／ 太 adj 了 ／ 不太 adj",
    funcao="Indicar a intensidade",
    modo="非常 = muitíssimo; 太…了 = demais (ou exclamação); 不太 = não muito",
    ex=["这个菜|非常|好吃|—|—|Zhège cài fēicháng hǎochī.|Este prato é delicioso.",
        "这件衣服|太|贵|—|了|Zhè jiàn yīfu tài guì le!|Esta roupa é cara demais!",
        "今天|不太|热|—|—|Jīntiān bú tài rè.|Hoje não está muito quente.",
        "中文|太|难|—|了|Zhōngwén tài nán le!|O chinês é difícil demais!"],
    wrong="这件衣服太贵。", right="这件衣服太贵了！",
    erro="Esquecer 了 depois de 太 + adjetivo. Na fala, 太 vem quase sempre acompanhado de 了 no fim.",
    obs="太好了！ = Que ótimo! — exclamação muito usada."),
  ]),
 dict(n=5, t="我七点起床。", py="Wǒ qī diǎn qǐchuáng.", pt="Eu me levanto às sete.",
  obj=["Posicionar expressões de tempo antes do verbo",
       "Indicar ação concluída com 了",
       "Negar ações passadas com 没(有)"],
  pts=[
   dict(title="Tempo antes do verbo", forma="S + tempo + V (+ O)",
    funcao="Dizer quando algo acontece (hábitos e planos)",
    modo="Afirmativo; o verbo não se conjuga — o tempo vem das palavras de tempo",
    ex=["我|七点|起床|—|—|Wǒ qī diǎn qǐchuáng.|Eu me levanto às sete.",
        "马克|每天|学习|中文|—|Mǎkè měitiān xuéxí Zhōngwén.|O Mark estuda chinês todo dia.",
        "我|明天|去|北京|—|Wǒ míngtiān qù Běijīng.|Amanhã vou a Pequim.",
        "她|晚上十一点|睡觉|—|—|Tā wǎnshang shíyī diǎn shuìjiào.|Ela dorme às onze da noite."],
    wrong="我起床七点。", right="我七点起床。",
    erro="Colocar o horário depois do verbo, como em \"acordo às sete\". Em chinês, o tempo vem antes do verbo.",
    obs="Do maior para o menor: 明天早上七点 (amanhã de manhã às sete)."),
   dict(title="Ação concluída com 了", forma="S + V + O + 了",
    funcao="Indicar que uma ação aconteceu e terminou",
    modo="Afirmativo; 了 marca conclusão, não \"tempo passado\"",
    ex=["我|昨天|看|电影|了|Wǒ zuótiān kàn diànyǐng le.|Ontem eu vi um filme.",
        "她|—|买|苹果|了|Tā mǎi píngguǒ le.|Ela comprou maçãs.",
        "我|—|吃|饭|了|Wǒ chī fàn le.|Eu já comi.",
        "马克|—|来|—|了|Mǎkè lái le.|O Mark chegou."],
    wrong="我每天看了电视。", right="我每天看电视。",
    erro="Usar 了 em hábitos. 了 marca uma ação concluída; com 每天 e outras rotinas, ele não entra.",
    obs="Passado sem conclusão também dispensa 了: 以前我常常去 (antes eu ia sempre), 昨天很冷 (ontem fez frio)."),
   dict(title="Negação do passado: 没(有)", forma="S + 没(有) + V + O",
    funcao="Dizer que algo não aconteceu",
    modo="Negativo; 没 substitui 不 e o 了 desaparece",
    ex=["我|昨天没|去|学校|—|Wǒ zuótiān méi qù xuéxiào.|Ontem não fui à escola.",
        "她|没|吃|早饭|—|Tā méi chī zǎofàn.|Ela não tomou café da manhã.",
        "马克|没有|来|—|—|Mǎkè méiyǒu lái.|O Mark não veio.",
        "我|昨天没|看|电视|—|Wǒ zuótiān méi kàn diànshì.|Ontem não vi TV."],
    wrong="我昨天没去学校了。", right="我昨天没去学校。",
    erro="Manter 了 na negativa. Com 没, o 了 sai: 没去, nunca 没去了.",
    obs="不 = não (agora, hábito, futuro); 没 = não (aconteceu). 我不去 = não vou; 我没去 = não fui."),
  ]),
 dict(n=6, t="昨天你去哪儿了？", py="Zuótiān nǐ qù nǎr le?", pt="Aonde você foi ontem?",
  obj=["Indicar destino com 去 / 来 / 回 + lugar",
       "Usar a ordem verbo + objeto (SVO)",
       "Indicar meio de transporte com 坐 / 骑 / 开"],
  pts=[
   dict(title="Destino: 去 / 来 / 回 + lugar", forma="S + 去/来/回 + lugar",
    funcao="Dizer para onde alguém vai, vem ou volta",
    modo="Afirmativo; o lugar vem direto depois do verbo, sem preposição",
    ex=["我|明天|去|上海|—|Wǒ míngtiān qù Shànghǎi.|Amanhã vou a Xangai.",
        "你|昨天|去|哪儿|了|Nǐ zuótiān qù nǎr le?|Aonde você foi ontem?",
        "马克|下个月|回|美国|—|Mǎkè xià ge yuè huí Měiguó.|O Mark volta aos EUA no mês que vem.",
        "她|—|来|我家|了|Tā lái wǒ jiā le.|Ela veio à minha casa."],
    wrong="我去在上海。", right="我去上海。",
    erro="Colocar 在 entre o verbo e o destino, como \"ir para\". Com 去 / 来 / 回, o lugar entra direto.",
    obs="去 = ir (afastando-se); 来 = vir (até quem fala); 回 = voltar (para casa, para o país)."),
   dict(title="Verbo + objeto", forma="S + V + O",
    funcao="Indicar sobre o que recai a ação",
    modo="Afirmativo; ordem SVO, como no português",
    ex=["我|—|喝|茶|—|Wǒ hē chá.|Eu bebo chá.",
        "马克|—|看|书|—|Mǎkè kàn shū.|O Mark lê.",
        "我们|晚上|吃|饺子|—|Wǒmen wǎnshang chī jiǎozi.|À noite comemos jiaozi.",
        "她|—|听|音乐|—|Tā tīng yīnyuè.|Ela ouve música."],
    wrong="我茶喝。", right="我喝茶。",
    erro="Colocar o objeto antes do verbo. O chinês é SVO: sujeito, verbo, objeto.",
    obs="Muitos \"verbos\" já trazem objeto: 吃饭 (comer), 睡觉 (dormir), 说话 (falar)."),
   dict(title="Transporte: 坐 / 骑 / 开", forma="S + 坐/骑/开 + veículo + 去 + lugar",
    funcao="Dizer como alguém se desloca",
    modo="Afirmativo; o meio de transporte vem antes do destino",
    ex=["我|坐地铁|去|学校|—|Wǒ zuò dìtiě qù xuéxiào.|Vou à escola de metrô.",
        "马克|坐飞机|去|北京|—|Mǎkè zuò fēijī qù Běijīng.|O Mark vai a Pequim de avião.",
        "她|骑自行车|去|公司|—|Tā qí zìxíngchē qù gōngsī.|Ela vai ao trabalho de bicicleta.",
        "你|怎么|去|机场|—|Nǐ zěnme qù jīchǎng?|Como você vai ao aeroporto?"],
    wrong="我去学校坐地铁。", right="我坐地铁去学校。",
    erro="Deixar o meio de transporte no fim, como em \"vou à escola de metrô\". O meio vem antes do destino.",
    obs="坐 = ir sentado (ônibus, metrô, avião, táxi); 骑 = montado (bicicleta, moto); 开 = dirigindo (开车)."),
  ]),
 dict(n=7, t="我用筷子吃饭。", py="Wǒ yòng kuàizi chī fàn.", pt="Eu como com hashi.",
  obj=["Indicar instrumento e idioma com 用",
       "Dar e presentear com 给 / 送 + pessoa + coisa",
       "Dizer que algo já aconteceu (已经…了) ou ainda não (还没…呢)"],
  pts=[
   dict(title="Instrumento: 用", forma="S + 用 + instrumento + V + O",
    funcao="Dizer com que se faz algo (ferramenta, aparelho, idioma)",
    modo="Afirmativo; 用 + instrumento fica antes do verbo principal",
    ex=["我|用筷子|吃|饭|—|Wǒ yòng kuàizi chī fàn.|Eu como com hashi.",
        "马克|用中文|写|信|—|Mǎkè yòng Zhōngwén xiě xìn.|O Mark escreve cartas em chinês.",
        "她|用手机|买|票|—|Tā yòng shǒujī mǎi piào.|Ela compra passagens pelo celular.",
        "我们|用电脑|学习|—|—|Wǒmen yòng diànnǎo xuéxí.|Estudamos no computador."],
    wrong="我吃饭用筷子。", right="我用筷子吃饭。",
    erro="Colocar o instrumento depois do verbo. 用 + instrumento vem antes da ação.",
    obs="Em chinês, o idioma também é instrumento: 用中文说 (dizer em chinês)."),
   dict(title="Dar: 给 / 送", forma="S + 给/送 + pessoa + coisa",
    funcao="Dizer quem dá o quê a quem",
    modo="Afirmativo; dois objetos: primeiro a pessoa, depois a coisa",
    ex=["我|—|给|他一本书|—|Wǒ gěi tā yì běn shū.|Eu dou um livro a ele.",
        "马克|—|送|安娜一束花|了|Mǎkè sòng Ānnà yí shù huā le.|O Mark deu um buquê de flores à Ana.",
        "妈妈|—|给|我钱|了|Māma gěi wǒ qián le.|A mamãe me deu dinheiro.",
        "老师|—|给|我们作业|了|Lǎoshī gěi wǒmen zuòyè le.|O professor nos passou dever de casa."],
    wrong="我给一本书他。", right="我给他一本书。",
    erro="Inverter a ordem dos objetos. Com 给 e 送, a pessoa vem antes da coisa.",
    obs="送 = dar de presente; 给 = dar, entregar (geral)."),
   dict(title="已经…了 ／ 还没…呢", forma="S + 已经 + V + 了 ／ S + 还没 + V + 呢",
    funcao="Dizer que algo já aconteceu ou ainda não",
    modo="已经 combina com 了; 还没 combina com 呢 (opcional)",
    ex=["我|已经|吃|饭|了|Wǒ yǐjīng chī fàn le.|Eu já comi.",
        "他|已经|回|家|了|Tā yǐjīng huí jiā le.|Ele já voltou para casa.",
        "我|还没|做|作业|呢|Wǒ hái méi zuò zuòyè ne.|Ainda não fiz o dever.",
        "电影|还没|开始|—|呢|Diànyǐng hái méi kāishǐ ne.|O filme ainda não começou."],
    wrong="我已经没吃饭。", right="我还没吃饭呢。",
    erro="Usar 已经 com negativo para \"ainda não\". 已经 é \"já\"; \"ainda não\" é 还没.",
    obs="Pergunta: 你吃饭了吗？ Respostas: 吃了 (já comi) ／ 还没呢 (ainda não)."),
  ]),
 dict(n=8, t="这本书很有意思。", py="Zhè běn shū hěn yǒu yìsi.", pt="Este livro é interessante.",
  obj=["Usar classificadores (个、本、杯、张) com 这 / 那 / números",
       "Modificar substantivos com adjetivo + 的",
       "Expressar posse com 有 e negá-la com 没有"],
  pts=[
   dict(title="Classificadores", forma="这/那/número + classificador + N",
    funcao="Contar e apontar objetos",
    modo="Obrigatório: entre 这 / 那 / número e o substantivo sempre entra um classificador",
    ex=["这本书|很|有意思|—|—|Zhè běn shū hěn yǒu yìsi.|Este livro é interessante.",
        "我|—|要|一杯咖啡|—|Wǒ yào yì bēi kāfēi.|Eu quero um café.",
        "那个人|—|是|我朋友|—|Nàge rén shì wǒ péngyou.|Aquela pessoa é minha amiga.",
        "我|—|买|两张票|—|Wǒ mǎi liǎng zhāng piào.|Eu compro duas passagens."],
    wrong="这书很有意思。", right="这本书很有意思。",
    erro="Omitir o classificador. Entre 这 / 那 / número e o substantivo, o classificador é obrigatório.",
    obs="个 é o coringa, mas cada grupo tem o seu: 本 (livros), 杯 (copos), 张 (coisas planas), 件 (roupas)."),
   dict(title="Adjetivo + 的 + substantivo", forma="(很) adj + 的 + N",
    funcao="Descrever um substantivo dentro da frase",
    modo="Adjetivo com 很 ou de duas sílabas leva 的; adjetivos curtos e comuns dispensam (新书、好人)",
    ex=["她|—|是|很好的老师|—|Tā shì hěn hǎo de lǎoshī.|Ela é uma ótima professora.",
        "这|—|是|很有意思的电影|—|Zhè shì hěn yǒu yìsi de diànyǐng.|Este é um filme interessante.",
        "我|—|有|一个新手机|—|Wǒ yǒu yí ge xīn shǒujī.|Eu tenho um celular novo.",
        "北京|—|是|漂亮的城市|—|Běijīng shì piàoliang de chéngshì.|Pequim é uma cidade bonita."],
    wrong="她是老师很好。", right="她是很好的老师。",
    erro="Colocar o adjetivo depois do substantivo, como em \"professora boa\". Em chinês, o modificador vem sempre antes.",
    obs="新书、好人、大房子: adjetivos de uma sílaba muito comuns ligam direto, sem 的."),
   dict(title="Posse: 有 / 没有", forma="S + 有 / 没有 + N",
    funcao="Dizer o que alguém tem ou não tem",
    modo="Afirmativo/negativo; a negativa de 有 é sempre 没有 (nunca 不有)",
    ex=["我|—|有|一个哥哥|—|Wǒ yǒu yí ge gēge.|Tenho um irmão mais velho.",
        "马克|—|没有|车|—|Mǎkè méiyǒu chē.|O Mark não tem carro.",
        "你|—|有|时间|吗|Nǐ yǒu shíjiān ma?|Você tem tempo?",
        "她|—|没有|钱|—|Tā méiyǒu qián.|Ela não tem dinheiro."],
    wrong="我不有车。", right="我没有车。",
    erro="Negar 有 com 不. 有 é o único verbo que nega sempre com 没: 没有.",
    obs="有意思 = interessante (literalmente \"ter sentido\"); 没意思 = sem graça."),
  ]),
 dict(n=9, t="我喜欢中国菜。", py="Wǒ xǐhuan Zhōngguó cài.", pt="Eu gosto de comida chinesa.",
  obj=["Falar de gostos com 喜欢 + substantivo ou verbo",
       "Falar de habilidades aprendidas com 会",
       "Dar motivos com 因为…所以… e perguntar com 为什么"],
  pts=[
   dict(title="Gostos: 喜欢", forma="S + 喜欢 + N ／ V + O",
    funcao="Dizer do que se gosta",
    modo="Afirmativo/negativo (不喜欢); 喜欢 aceita substantivo ou verbo direto",
    ex=["我|—|喜欢|中国菜|—|Wǒ xǐhuan Zhōngguó cài.|Eu gosto de comida chinesa.",
        "马克|—|喜欢|喝咖啡|—|Mǎkè xǐhuan hē kāfēi.|O Mark gosta de tomar café.",
        "她|不|喜欢|下雨天|—|Tā bù xǐhuan xiàyǔ tiān.|Ela não gosta de dias de chuva.",
        "你|—|喜欢|什么运动|—|Nǐ xǐhuan shénme yùndòng?|De que esporte você gosta?"],
    wrong="我喜欢很中国菜。", right="我很喜欢中国菜。",
    erro="Colocar 很 depois de 喜欢. Advérbios de grau vêm antes do verbo: 很喜欢 = gosto muito.",
    obs="爱 (ài) é mais forte que 喜欢: 我爱你 = eu te amo."),
   dict(title="Habilidade aprendida: 会", forma="S + 会 + V + O",
    funcao="Dizer o que alguém sabe fazer (habilidade aprendida)",
    modo="Afirmativo/negativo (不会); 会 vem antes do verbo principal",
    ex=["我|会|说|中文|—|Wǒ huì shuō Zhōngwén.|Eu sei falar chinês.",
        "马克|会|游泳|—|—|Mǎkè huì yóuyǒng.|O Mark sabe nadar.",
        "她|不会|开|车|—|Tā bú huì kāi chē.|Ela não sabe dirigir.",
        "你|会|做|中国菜|吗|Nǐ huì zuò Zhōngguó cài ma?|Você sabe fazer comida chinesa?"],
    wrong="我知道说中文。", right="我会说中文。",
    erro="Traduzir \"saber falar\" com 知道. 知道 = saber uma informação; habilidade aprendida é 会.",
    obs="会 também indica previsão: 明天会下雨 (amanhã vai chover)."),
   dict(title="Razão: 因为…所以… ／ 为什么", forma="(S) 因为 + causa，所以 + consequência",
    funcao="Explicar o motivo; perguntar com 为什么",
    modo="Afirmativo; 因为 e 所以 podem aparecer juntos (diferente do português)",
    ex=["你|为什么|学|中文|—|Nǐ wèishénme xué Zhōngwén?|Por que você estuda chinês?",
        "我|因为喜欢中国|学|中文|—|Wǒ yīnwèi xǐhuan Zhōngguó xué Zhōngwén.|Estudo chinês porque gosto da China.",
        "她|因为生病没|来|上课|—|Tā yīnwèi shēngbìng méi lái shàngkè.|Ela não veio à aula porque estava doente.",
        "我|因为太累不想|去|—|—|Wǒ yīnwèi tài lèi bù xiǎng qù.|Não quero ir porque estou muito cansado."],
    wrong="我学中文，所以我喜欢中国。", right="因为我喜欢中国，所以我学中文。",
    erro="Inverter causa e consequência. 因为 introduz a causa e 所以 o resultado; a causa vem primeiro.",
    obs="为什么？ → 因为…: Por quê? → Porque…."),
  ]),
 dict(n=10, t="桌子上有一本书。", py="Zhuōzi shang yǒu yì běn shū.", pt="Há um livro em cima da mesa.",
  obj=["Expressar existência com lugar + 有 + N",
       "Localizar com 上 / 下面 / 里 / 前面 / 后面 / 旁边",
       "Dizer onde algo conhecido está com N + 在 + lugar"],
  pts=[
   dict(title="Existência: lugar + 有 + N", forma="Lugar + 有 + (número + cl.) + N",
    funcao="Dizer o que há em um lugar",
    modo="Afirmativo/negativo (没有); o lugar abre a frase e a coisa é nova na conversa",
    ex=["桌子上|—|有|一本书|—|Zhuōzi shang yǒu yì běn shū.|Há um livro em cima da mesa.",
        "学校旁边|—|有|一个银行|—|Xuéxiào pángbiān yǒu yí ge yínháng.|Ao lado da escola há um banco.",
        "房间里|—|没有|人|—|Fángjiān li méiyǒu rén.|Não há ninguém no quarto.",
        "冰箱里|—|有|什么|—|Bīngxiāng li yǒu shénme?|O que há na geladeira?"],
    wrong="在桌子上有一本书。", right="桌子上有一本书。",
    erro="Abrir a frase com 在, como \"em cima da mesa há…\". Na estrutura de existência, o lugar entra sozinho.",
    obs="有 serve para coisas, pessoas e animais: não há verbos diferentes para seres vivos."),
   dict(title="Posição: referência + localizador", forma="N + 上/下面/里/前面/后面/旁边",
    funcao="Indicar posição em relação a uma referência",
    modo="O localizador vem DEPOIS da referência (mesa + em cima = 桌子上)",
    ex=["猫|—|在|桌子下面|—|Māo zài zhuōzi xiàmiàn.|O gato está embaixo da mesa.",
        "书|—|在|包里|—|Shū zài bāo li.|O livro está na bolsa.",
        "商店|—|在|银行后面|—|Shāngdiàn zài yínháng hòumiàn.|A loja fica atrás do banco.",
        "我家|—|在|学校前面|—|Wǒ jiā zài xuéxiào qiánmiàn.|Minha casa fica em frente à escola."],
    wrong="猫在下面桌子。", right="猫在桌子下面。",
    erro="Colocar o localizador antes da referência, como em \"embaixo da mesa\". Em chinês: referência + localizador.",
    obs="里 (dentro) e 上 (em cima) costumam ser curtos e átonos: 包里、桌子上."),
   dict(title="Localização: N + 在 + lugar", forma="N (conhecido) + 在 + lugar",
    funcao="Dizer onde está uma coisa ou pessoa já conhecida",
    modo="Afirmativo/negativo (不在); pergunta: 在哪儿？",
    ex=["我的手机|—|在|桌子上|—|Wǒ de shǒujī zài zhuōzi shang.|Meu celular está em cima da mesa.",
        "妈妈|—|在|家|—|Māma zài jiā.|A mamãe está em casa.",
        "马克|不|在|办公室|—|Mǎkè bú zài bàngōngshì.|O Mark não está no escritório.",
        "你的钥匙|—|在|哪儿|—|Nǐ de yàoshi zài nǎr?|Onde estão suas chaves?"],
    wrong="桌子上在我的手机。", right="我的手机在桌子上。",
    erro="Misturar as duas estruturas. Coisa nova: lugar + 有 + coisa; coisa conhecida: coisa + 在 + lugar.",
    obs="有 apresenta algo novo (há um livro); 在 localiza algo já mencionado (o livro está…)."),
  ]),
 dict(n=11, t="我有两个妹妹。", py="Wǒ yǒu liǎng ge mèimei.", pt="Tenho duas irmãs mais novas.",
  obj=["Contar com números e diferenciar 二 de 两",
       "Perguntar quantidades com 几 e 多少",
       "Expressar frequência com 次"],
  pts=[
   dict(title="Números e 两", forma="两 + classificador + N",
    funcao="Contar pessoas e coisas",
    modo="Antes de classificador, \"dois\" é 两 (não 二)",
    ex=["我|—|有|两个妹妹|—|Wǒ yǒu liǎng ge mèimei.|Tenho duas irmãs mais novas.",
        "桌子上|—|有|三本书|—|Zhuōzi shang yǒu sān běn shū.|Há três livros na mesa.",
        "我们班|—|有|二十个学生|—|Wǒmen bān yǒu èrshí ge xuésheng.|Nossa turma tem vinte alunos.",
        "我|—|要|两杯茶|—|Wǒ yào liǎng bēi chá.|Quero dois chás."],
    wrong="我有二个妹妹。", right="我有两个妹妹。",
    erro="Usar 二 antes de classificador. Para contar coisas, \"dois\" é 两; 二 serve para contar em sequência e dentro de números (十二).",
    obs="12 = 十二 (não 十两); 20 = 二十; 200 = 两百 ou 二百."),
   dict(title="Quantos: 几 / 多少", forma="几 + cl. + N？ ／ 多少 + N？",
    funcao="Perguntar quantidade",
    modo="几 = número pequeno (até cerca de 10) e pede classificador; 多少 = qualquer número",
    ex=["你|—|有|几个孩子|—|Nǐ yǒu jǐ ge háizi?|Quantos filhos você tem?",
        "你们班|—|有|多少学生|—|Nǐmen bān yǒu duōshao xuésheng?|Quantos alunos tem a sua turma?",
        "现在|—|—|几点|—|Xiànzài jǐ diǎn?|Que horas são?",
        "你|—|要|几杯咖啡|—|Nǐ yào jǐ bēi kāfēi?|Quantos cafés você quer?"],
    wrong="你有几孩子？", right="你有几个孩子？",
    erro="Esquecer o classificador depois de 几. 几 sempre pede classificador; 多少 pode dispensá-lo.",
    obs="Idade: 你几岁？ (para crianças) ／ 你多大？ (para adultos)."),
   dict(title="Frequência: … 次", forma="S + período + V + número + 次 (+ O)",
    funcao="Dizer quantas vezes algo acontece",
    modo="O período vem antes do verbo; o número de vezes, depois",
    ex=["我|一个星期|去|两次健身房|—|Wǒ yí ge xīngqī qù liǎng cì jiànshēnfáng.|Vou à academia duas vezes por semana.",
        "她|每天|吃|三次药|—|Tā měitiān chī sān cì yào.|Ela toma remédio três vezes por dia.",
        "我们|一年|见|一次|—|Wǒmen yì nián jiàn yí cì.|Nós nos vemos uma vez por ano.",
        "你|一天|喝|几次咖啡|—|Nǐ yì tiān hē jǐ cì kāfēi?|Quantas vezes por dia você toma café?"],
    wrong="我两次一个星期去健身房。", right="我一个星期去两次健身房。",
    erro="Colocar o número de vezes antes do verbo. O período (一个星期) vem antes; a frequência (两次), depois do verbo.",
    obs="次 = vezes; 遍 (biàn) = vezes do começo ao fim: 再说一遍 (diga de novo)."),
  ]),
 dict(n=12, t="今天比昨天冷。", py="Jīntiān bǐ zuótiān lěng.", pt="Hoje está mais frio que ontem.",
  obj=["Descrever o passado com adjetivos, sem 了 nem 是",
       "Comparar com 比",
       "Usar 最 (o mais) e 没有…那么 (não tão… quanto)"],
  pts=[
   dict(title="Adjetivo no passado", forma="(tempo) + S + 很 adj",
    funcao="Descrever como algo era ou estava",
    modo="Afirmativo; o adjetivo não muda no passado — basta a palavra de tempo",
    ex=["昨天|很|冷|—|—|Zuótiān hěn lěng.|Ontem fez frio.",
        "我|上个星期很|忙|—|—|Wǒ shàng ge xīngqī hěn máng.|Semana passada eu estava ocupado.",
        "那个电影|非常|好看|—|—|Nàge diànyǐng fēicháng hǎokàn.|Aquele filme foi ótimo.",
        "她|以前很|瘦|—|—|Tā yǐqián hěn shòu.|Antes ela era magra."],
    wrong="昨天是很冷。", right="昨天很冷。",
    erro="Usar 是 para formar \"estava / era\". O adjetivo não leva 是 nem muda de forma; o tempo vem de 昨天.",
    obs="Com 了, o sentido muda para \"ficou\": 天冷了 = esfriou (Lição 19)."),
   dict(title="Comparação: A 比 B adj", forma="A + 比 + B + adj (+ diferença)",
    funcao="Dizer que A é mais … que B",
    modo="Afirmativo; não se usa 很 / 非常 com 比; para intensificar: 多了 ou 一点儿",
    ex=["今天|比昨天|冷|—|—|Jīntiān bǐ zuótiān lěng.|Hoje está mais frio que ontem.",
        "哥哥|比我|高|—|—|Gēge bǐ wǒ gāo.|Meu irmão é mais alto que eu.",
        "这个|比那个|贵|一点儿|—|Zhège bǐ nàge guì yìdiǎnr.|Este é um pouco mais caro que aquele.",
        "上海|比北京|热|多了|—|Shànghǎi bǐ Běijīng rè duō le.|Xangai é bem mais quente que Pequim."],
    wrong="今天比昨天很冷。", right="今天比昨天冷多了。",
    erro="Usar 很 ou 非常 numa frase com 比. Para dizer \"muito mais\", coloque 多了 depois do adjetivo.",
    obs="A negativa \"não tão… quanto\" usa 没有 (ponto C), não 比."),
   dict(title="最 e 没有…那么", forma="最 + adj ／ A + 没有 + B + (那么) adj",
    funcao="Superlativo e comparação negativa",
    modo="最 = o mais; 没有…那么 = não tão… quanto",
    ex=["她|最|喜欢|熊猫|—|Tā zuì xǐhuan xióngmāo.|O que ela mais gosta é de panda.",
        "这个菜|最|好吃|—|—|Zhège cài zuì hǎochī.|Este prato é o mais gostoso.",
        "今天|没有昨天那么|冷|—|—|Jīntiān méiyǒu zuótiān nàme lěng.|Hoje não está tão frio quanto ontem.",
        "我|没有哥哥那么|高|—|—|Wǒ méiyǒu gēge nàme gāo.|Não sou tão alto quanto meu irmão."],
    wrong="我比哥哥不高。", right="我没有哥哥那么高。",
    erro="Negar dentro da frase com 比. Para \"não tão… quanto\", use 没有…(那么) + adjetivo.",
    obs="最 entra antes de adjetivos e de verbos de sentimento: 最好、最喜欢."),
  ]),
]
